// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package use_protobuf.blog1;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:use_protobuf.blog1.CMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string msghead = 1;</code>
     * @return Whether the msghead field is set.
     */
    boolean hasMsghead();
    /**
     * <code>required string msghead = 1;</code>
     * @return The msghead.
     */
    String getMsghead();
    /**
     * <code>required string msghead = 1;</code>
     * @return The bytes for msghead.
     */
    com.google.protobuf.ByteString
        getMsgheadBytes();

    /**
     * <code>required string msgbody = 2;</code>
     * @return Whether the msgbody field is set.
     */
    boolean hasMsgbody();
    /**
     * <code>required string msgbody = 2;</code>
     * @return The msgbody.
     */
    String getMsgbody();
    /**
     * <code>required string msgbody = 2;</code>
     * @return The bytes for msgbody.
     */
    com.google.protobuf.ByteString
        getMsgbodyBytes();
  }
  /**
   * Protobuf type {@code use_protobuf.blog1.CMsg}
   */
  public  static final class CMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:use_protobuf.blog1.CMsg)
      CMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CMsg.newBuilder() to construct.
    private CMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CMsg() {
      msghead_ = "";
      msgbody_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msghead_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msgbody_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_use_protobuf_blog1_CMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_use_protobuf_blog1_CMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CMsg.class, Builder.class);
    }

    private int bitField0_;
    public static final int MSGHEAD_FIELD_NUMBER = 1;
    private volatile Object msghead_;
    /**
     * <code>required string msghead = 1;</code>
     * @return Whether the msghead field is set.
     */
    public boolean hasMsghead() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string msghead = 1;</code>
     * @return The msghead.
     */
    public String getMsghead() {
      Object ref = msghead_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msghead_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msghead = 1;</code>
     * @return The bytes for msghead.
     */
    public com.google.protobuf.ByteString
        getMsgheadBytes() {
      Object ref = msghead_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msghead_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGBODY_FIELD_NUMBER = 2;
    private volatile Object msgbody_;
    /**
     * <code>required string msgbody = 2;</code>
     * @return Whether the msgbody field is set.
     */
    public boolean hasMsgbody() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string msgbody = 2;</code>
     * @return The msgbody.
     */
    public String getMsgbody() {
      Object ref = msgbody_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgbody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgbody = 2;</code>
     * @return The bytes for msgbody.
     */
    public com.google.protobuf.ByteString
        getMsgbodyBytes() {
      Object ref = msgbody_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgbody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsghead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgbody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msghead_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgbody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msghead_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgbody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CMsg)) {
        return super.equals(obj);
      }
      CMsg other = (CMsg) obj;

      if (hasMsghead() != other.hasMsghead()) return false;
      if (hasMsghead()) {
        if (!getMsghead()
            .equals(other.getMsghead())) return false;
      }
      if (hasMsgbody() != other.hasMsgbody()) return false;
      if (hasMsgbody()) {
        if (!getMsgbody()
            .equals(other.getMsgbody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsghead()) {
        hash = (37 * hash) + MSGHEAD_FIELD_NUMBER;
        hash = (53 * hash) + getMsghead().hashCode();
      }
      if (hasMsgbody()) {
        hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
        hash = (53 * hash) + getMsgbody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code use_protobuf.blog1.CMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:use_protobuf.blog1.CMsg)
        CMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_use_protobuf_blog1_CMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_use_protobuf_blog1_CMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CMsg.class, Builder.class);
      }

      // Construct using use_protobuf.blog1.Msg.CMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msghead_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msgbody_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_use_protobuf_blog1_CMsg_descriptor;
      }

      @Override
      public CMsg getDefaultInstanceForType() {
        return CMsg.getDefaultInstance();
      }

      @Override
      public CMsg build() {
        CMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CMsg buildPartial() {
        CMsg result = new CMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msghead_ = msghead_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgbody_ = msgbody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CMsg) {
          return mergeFrom((CMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CMsg other) {
        if (other == CMsg.getDefaultInstance()) return this;
        if (other.hasMsghead()) {
          bitField0_ |= 0x00000001;
          msghead_ = other.msghead_;
          onChanged();
        }
        if (other.hasMsgbody()) {
          bitField0_ |= 0x00000002;
          msgbody_ = other.msgbody_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasMsghead()) {
          return false;
        }
        if (!hasMsgbody()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object msghead_ = "";
      /**
       * <code>required string msghead = 1;</code>
       * @return Whether the msghead field is set.
       */
      public boolean hasMsghead() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string msghead = 1;</code>
       * @return The msghead.
       */
      public String getMsghead() {
        Object ref = msghead_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msghead_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string msghead = 1;</code>
       * @return The bytes for msghead.
       */
      public com.google.protobuf.ByteString
          getMsgheadBytes() {
        Object ref = msghead_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msghead_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msghead = 1;</code>
       * @param value The msghead to set.
       * @return This builder for chaining.
       */
      public Builder setMsghead(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msghead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msghead = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsghead() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msghead_ = getDefaultInstance().getMsghead();
        onChanged();
        return this;
      }
      /**
       * <code>required string msghead = 1;</code>
       * @param value The bytes for msghead to set.
       * @return This builder for chaining.
       */
      public Builder setMsgheadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msghead_ = value;
        onChanged();
        return this;
      }

      private Object msgbody_ = "";
      /**
       * <code>required string msgbody = 2;</code>
       * @return Whether the msgbody field is set.
       */
      public boolean hasMsgbody() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string msgbody = 2;</code>
       * @return The msgbody.
       */
      public String getMsgbody() {
        Object ref = msgbody_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgbody_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string msgbody = 2;</code>
       * @return The bytes for msgbody.
       */
      public com.google.protobuf.ByteString
          getMsgbodyBytes() {
        Object ref = msgbody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgbody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgbody = 2;</code>
       * @param value The msgbody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgbody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgbody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgbody = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgbody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgbody_ = getDefaultInstance().getMsgbody();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgbody = 2;</code>
       * @param value The bytes for msgbody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgbodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgbody_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:use_protobuf.blog1.CMsg)
    }

    // @@protoc_insertion_point(class_scope:use_protobuf.blog1.CMsg)
    private static final CMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CMsg();
    }

    public static CMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<CMsg>
        PARSER = new com.google.protobuf.AbstractParser<CMsg>() {
      @Override
      public CMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public CMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CMsgHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:use_protobuf.blog1.CMsgHead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 msglen = 1;</code>
     * @return Whether the msglen field is set.
     */
    boolean hasMsglen();
    /**
     * <code>required int32 msglen = 1;</code>
     * @return The msglen.
     */
    int getMsglen();

    /**
     * <code>required int32 msgtype = 2;</code>
     * @return Whether the msgtype field is set.
     */
    boolean hasMsgtype();
    /**
     * <code>required int32 msgtype = 2;</code>
     * @return The msgtype.
     */
    int getMsgtype();

    /**
     * <code>required int32 msgseq = 3;</code>
     * @return Whether the msgseq field is set.
     */
    boolean hasMsgseq();
    /**
     * <code>required int32 msgseq = 3;</code>
     * @return The msgseq.
     */
    int getMsgseq();

    /**
     * <code>required int32 termversion = 4;</code>
     * @return Whether the termversion field is set.
     */
    boolean hasTermversion();
    /**
     * <code>required int32 termversion = 4;</code>
     * @return The termversion.
     */
    int getTermversion();

    /**
     * <code>required int32 msgres = 5;</code>
     * @return Whether the msgres field is set.
     */
    boolean hasMsgres();
    /**
     * <code>required int32 msgres = 5;</code>
     * @return The msgres.
     */
    int getMsgres();

    /**
     * <code>required string termid = 6;</code>
     * @return Whether the termid field is set.
     */
    boolean hasTermid();
    /**
     * <code>required string termid = 6;</code>
     * @return The termid.
     */
    String getTermid();
    /**
     * <code>required string termid = 6;</code>
     * @return The bytes for termid.
     */
    com.google.protobuf.ByteString
        getTermidBytes();
  }
  /**
   * Protobuf type {@code use_protobuf.blog1.CMsgHead}
   */
  public  static final class CMsgHead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:use_protobuf.blog1.CMsgHead)
      CMsgHeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CMsgHead.newBuilder() to construct.
    private CMsgHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CMsgHead() {
      termid_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CMsgHead();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CMsgHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              msglen_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              msgtype_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgseq_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              termversion_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              msgres_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              termid_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_use_protobuf_blog1_CMsgHead_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_use_protobuf_blog1_CMsgHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CMsgHead.class, Builder.class);
    }

    private int bitField0_;
    public static final int MSGLEN_FIELD_NUMBER = 1;
    private int msglen_;
    /**
     * <code>required int32 msglen = 1;</code>
     * @return Whether the msglen field is set.
     */
    public boolean hasMsglen() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 msglen = 1;</code>
     * @return The msglen.
     */
    public int getMsglen() {
      return msglen_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgtype_;
    /**
     * <code>required int32 msgtype = 2;</code>
     * @return Whether the msgtype field is set.
     */
    public boolean hasMsgtype() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 msgtype = 2;</code>
     * @return The msgtype.
     */
    public int getMsgtype() {
      return msgtype_;
    }

    public static final int MSGSEQ_FIELD_NUMBER = 3;
    private int msgseq_;
    /**
     * <code>required int32 msgseq = 3;</code>
     * @return Whether the msgseq field is set.
     */
    public boolean hasMsgseq() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 msgseq = 3;</code>
     * @return The msgseq.
     */
    public int getMsgseq() {
      return msgseq_;
    }

    public static final int TERMVERSION_FIELD_NUMBER = 4;
    private int termversion_;
    /**
     * <code>required int32 termversion = 4;</code>
     * @return Whether the termversion field is set.
     */
    public boolean hasTermversion() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 termversion = 4;</code>
     * @return The termversion.
     */
    public int getTermversion() {
      return termversion_;
    }

    public static final int MSGRES_FIELD_NUMBER = 5;
    private int msgres_;
    /**
     * <code>required int32 msgres = 5;</code>
     * @return Whether the msgres field is set.
     */
    public boolean hasMsgres() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 msgres = 5;</code>
     * @return The msgres.
     */
    public int getMsgres() {
      return msgres_;
    }

    public static final int TERMID_FIELD_NUMBER = 6;
    private volatile Object termid_;
    /**
     * <code>required string termid = 6;</code>
     * @return Whether the termid field is set.
     */
    public boolean hasTermid() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string termid = 6;</code>
     * @return The termid.
     */
    public String getTermid() {
      Object ref = termid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          termid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string termid = 6;</code>
     * @return The bytes for termid.
     */
    public com.google.protobuf.ByteString
        getTermidBytes() {
      Object ref = termid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        termid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsglen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgseq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTermversion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgres()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTermid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, msglen_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, msgtype_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, msgseq_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, termversion_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, msgres_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, termid_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msglen_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgtype_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, msgseq_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, termversion_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, msgres_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, termid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CMsgHead)) {
        return super.equals(obj);
      }
      CMsgHead other = (CMsgHead) obj;

      if (hasMsglen() != other.hasMsglen()) return false;
      if (hasMsglen()) {
        if (getMsglen()
            != other.getMsglen()) return false;
      }
      if (hasMsgtype() != other.hasMsgtype()) return false;
      if (hasMsgtype()) {
        if (getMsgtype()
            != other.getMsgtype()) return false;
      }
      if (hasMsgseq() != other.hasMsgseq()) return false;
      if (hasMsgseq()) {
        if (getMsgseq()
            != other.getMsgseq()) return false;
      }
      if (hasTermversion() != other.hasTermversion()) return false;
      if (hasTermversion()) {
        if (getTermversion()
            != other.getTermversion()) return false;
      }
      if (hasMsgres() != other.hasMsgres()) return false;
      if (hasMsgres()) {
        if (getMsgres()
            != other.getMsgres()) return false;
      }
      if (hasTermid() != other.hasTermid()) return false;
      if (hasTermid()) {
        if (!getTermid()
            .equals(other.getTermid())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsglen()) {
        hash = (37 * hash) + MSGLEN_FIELD_NUMBER;
        hash = (53 * hash) + getMsglen();
      }
      if (hasMsgtype()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgtype();
      }
      if (hasMsgseq()) {
        hash = (37 * hash) + MSGSEQ_FIELD_NUMBER;
        hash = (53 * hash) + getMsgseq();
      }
      if (hasTermversion()) {
        hash = (37 * hash) + TERMVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getTermversion();
      }
      if (hasMsgres()) {
        hash = (37 * hash) + MSGRES_FIELD_NUMBER;
        hash = (53 * hash) + getMsgres();
      }
      if (hasTermid()) {
        hash = (37 * hash) + TERMID_FIELD_NUMBER;
        hash = (53 * hash) + getTermid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CMsgHead parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsgHead parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsgHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsgHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsgHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsgHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsgHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CMsgHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CMsgHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CMsgHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CMsgHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CMsgHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CMsgHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code use_protobuf.blog1.CMsgHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:use_protobuf.blog1.CMsgHead)
        CMsgHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_use_protobuf_blog1_CMsgHead_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_use_protobuf_blog1_CMsgHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CMsgHead.class, Builder.class);
      }

      // Construct using use_protobuf.blog1.Msg.CMsgHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msglen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgseq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        termversion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msgres_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        termid_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_use_protobuf_blog1_CMsgHead_descriptor;
      }

      @Override
      public CMsgHead getDefaultInstanceForType() {
        return CMsgHead.getDefaultInstance();
      }

      @Override
      public CMsgHead build() {
        CMsgHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CMsgHead buildPartial() {
        CMsgHead result = new CMsgHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msglen_ = msglen_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msgtype_ = msgtype_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.msgseq_ = msgseq_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.termversion_ = termversion_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.msgres_ = msgres_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.termid_ = termid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CMsgHead) {
          return mergeFrom((CMsgHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CMsgHead other) {
        if (other == CMsgHead.getDefaultInstance()) return this;
        if (other.hasMsglen()) {
          setMsglen(other.getMsglen());
        }
        if (other.hasMsgtype()) {
          setMsgtype(other.getMsgtype());
        }
        if (other.hasMsgseq()) {
          setMsgseq(other.getMsgseq());
        }
        if (other.hasTermversion()) {
          setTermversion(other.getTermversion());
        }
        if (other.hasMsgres()) {
          setMsgres(other.getMsgres());
        }
        if (other.hasTermid()) {
          bitField0_ |= 0x00000020;
          termid_ = other.termid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasMsglen()) {
          return false;
        }
        if (!hasMsgtype()) {
          return false;
        }
        if (!hasMsgseq()) {
          return false;
        }
        if (!hasTermversion()) {
          return false;
        }
        if (!hasMsgres()) {
          return false;
        }
        if (!hasTermid()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CMsgHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CMsgHead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msglen_ ;
      /**
       * <code>required int32 msglen = 1;</code>
       * @return Whether the msglen field is set.
       */
      public boolean hasMsglen() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 msglen = 1;</code>
       * @return The msglen.
       */
      public int getMsglen() {
        return msglen_;
      }
      /**
       * <code>required int32 msglen = 1;</code>
       * @param value The msglen to set.
       * @return This builder for chaining.
       */
      public Builder setMsglen(int value) {
        bitField0_ |= 0x00000001;
        msglen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msglen = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsglen() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msglen_ = 0;
        onChanged();
        return this;
      }

      private int msgtype_ ;
      /**
       * <code>required int32 msgtype = 2;</code>
       * @return Whether the msgtype field is set.
       */
      public boolean hasMsgtype() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 msgtype = 2;</code>
       * @return The msgtype.
       */
      public int getMsgtype() {
        return msgtype_;
      }
      /**
       * <code>required int32 msgtype = 2;</code>
       * @param value The msgtype to set.
       * @return This builder for chaining.
       */
      public Builder setMsgtype(int value) {
        bitField0_ |= 0x00000002;
        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgtype = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgtype_ = 0;
        onChanged();
        return this;
      }

      private int msgseq_ ;
      /**
       * <code>required int32 msgseq = 3;</code>
       * @return Whether the msgseq field is set.
       */
      public boolean hasMsgseq() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 msgseq = 3;</code>
       * @return The msgseq.
       */
      public int getMsgseq() {
        return msgseq_;
      }
      /**
       * <code>required int32 msgseq = 3;</code>
       * @param value The msgseq to set.
       * @return This builder for chaining.
       */
      public Builder setMsgseq(int value) {
        bitField0_ |= 0x00000004;
        msgseq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgseq = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgseq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgseq_ = 0;
        onChanged();
        return this;
      }

      private int termversion_ ;
      /**
       * <code>required int32 termversion = 4;</code>
       * @return Whether the termversion field is set.
       */
      public boolean hasTermversion() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 termversion = 4;</code>
       * @return The termversion.
       */
      public int getTermversion() {
        return termversion_;
      }
      /**
       * <code>required int32 termversion = 4;</code>
       * @param value The termversion to set.
       * @return This builder for chaining.
       */
      public Builder setTermversion(int value) {
        bitField0_ |= 0x00000008;
        termversion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 termversion = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTermversion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        termversion_ = 0;
        onChanged();
        return this;
      }

      private int msgres_ ;
      /**
       * <code>required int32 msgres = 5;</code>
       * @return Whether the msgres field is set.
       */
      public boolean hasMsgres() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 msgres = 5;</code>
       * @return The msgres.
       */
      public int getMsgres() {
        return msgres_;
      }
      /**
       * <code>required int32 msgres = 5;</code>
       * @param value The msgres to set.
       * @return This builder for chaining.
       */
      public Builder setMsgres(int value) {
        bitField0_ |= 0x00000010;
        msgres_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgres = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgres() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgres_ = 0;
        onChanged();
        return this;
      }

      private Object termid_ = "";
      /**
       * <code>required string termid = 6;</code>
       * @return Whether the termid field is set.
       */
      public boolean hasTermid() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string termid = 6;</code>
       * @return The termid.
       */
      public String getTermid() {
        Object ref = termid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            termid_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string termid = 6;</code>
       * @return The bytes for termid.
       */
      public com.google.protobuf.ByteString
          getTermidBytes() {
        Object ref = termid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          termid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string termid = 6;</code>
       * @param value The termid to set.
       * @return This builder for chaining.
       */
      public Builder setTermid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        termid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string termid = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTermid() {
        bitField0_ = (bitField0_ & ~0x00000020);
        termid_ = getDefaultInstance().getTermid();
        onChanged();
        return this;
      }
      /**
       * <code>required string termid = 6;</code>
       * @param value The bytes for termid to set.
       * @return This builder for chaining.
       */
      public Builder setTermidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        termid_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:use_protobuf.blog1.CMsgHead)
    }

    // @@protoc_insertion_point(class_scope:use_protobuf.blog1.CMsgHead)
    private static final CMsgHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CMsgHead();
    }

    public static CMsgHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<CMsgHead>
        PARSER = new com.google.protobuf.AbstractParser<CMsgHead>() {
      @Override
      public CMsgHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CMsgHead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CMsgHead> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CMsgHead> getParserForType() {
      return PARSER;
    }

    @Override
    public CMsgHead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CMsgRegOrBuilder extends
      // @@protoc_insertion_point(interface_extends:use_protobuf.blog1.CMsgReg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 area = 1;</code>
     * @return Whether the area field is set.
     */
    boolean hasArea();
    /**
     * <code>optional int32 area = 1;</code>
     * @return The area.
     */
    int getArea();

    /**
     * <code>optional int32 region = 2;</code>
     * @return Whether the region field is set.
     */
    boolean hasRegion();
    /**
     * <code>optional int32 region = 2;</code>
     * @return The region.
     */
    int getRegion();

    /**
     * <code>optional int32 shop = 3;</code>
     * @return Whether the shop field is set.
     */
    boolean hasShop();
    /**
     * <code>optional int32 shop = 3;</code>
     * @return The shop.
     */
    int getShop();

    /**
     * <code>optional int32 ret = 4;</code>
     * @return Whether the ret field is set.
     */
    boolean hasRet();
    /**
     * <code>optional int32 ret = 4;</code>
     * @return The ret.
     */
    int getRet();

    /**
     * <code>optional string termid = 5;</code>
     * @return Whether the termid field is set.
     */
    boolean hasTermid();
    /**
     * <code>optional string termid = 5;</code>
     * @return The termid.
     */
    String getTermid();
    /**
     * <code>optional string termid = 5;</code>
     * @return The bytes for termid.
     */
    com.google.protobuf.ByteString
        getTermidBytes();
  }
  /**
   * Protobuf type {@code use_protobuf.blog1.CMsgReg}
   */
  public  static final class CMsgReg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:use_protobuf.blog1.CMsgReg)
      CMsgRegOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CMsgReg.newBuilder() to construct.
    private CMsgReg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CMsgReg() {
      termid_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CMsgReg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CMsgReg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              area_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              region_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              shop_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ret_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              termid_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_use_protobuf_blog1_CMsgReg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_use_protobuf_blog1_CMsgReg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CMsgReg.class, Builder.class);
    }

    private int bitField0_;
    public static final int AREA_FIELD_NUMBER = 1;
    private int area_;
    /**
     * <code>optional int32 area = 1;</code>
     * @return Whether the area field is set.
     */
    public boolean hasArea() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 area = 1;</code>
     * @return The area.
     */
    public int getArea() {
      return area_;
    }

    public static final int REGION_FIELD_NUMBER = 2;
    private int region_;
    /**
     * <code>optional int32 region = 2;</code>
     * @return Whether the region field is set.
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 region = 2;</code>
     * @return The region.
     */
    public int getRegion() {
      return region_;
    }

    public static final int SHOP_FIELD_NUMBER = 3;
    private int shop_;
    /**
     * <code>optional int32 shop = 3;</code>
     * @return Whether the shop field is set.
     */
    public boolean hasShop() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 shop = 3;</code>
     * @return The shop.
     */
    public int getShop() {
      return shop_;
    }

    public static final int RET_FIELD_NUMBER = 4;
    private int ret_;
    /**
     * <code>optional int32 ret = 4;</code>
     * @return Whether the ret field is set.
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 ret = 4;</code>
     * @return The ret.
     */
    public int getRet() {
      return ret_;
    }

    public static final int TERMID_FIELD_NUMBER = 5;
    private volatile Object termid_;
    /**
     * <code>optional string termid = 5;</code>
     * @return Whether the termid field is set.
     */
    public boolean hasTermid() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string termid = 5;</code>
     * @return The termid.
     */
    public String getTermid() {
      Object ref = termid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          termid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string termid = 5;</code>
     * @return The bytes for termid.
     */
    public com.google.protobuf.ByteString
        getTermidBytes() {
      Object ref = termid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        termid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, area_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, region_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, shop_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, ret_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, termid_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, area_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, region_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, shop_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ret_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, termid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CMsgReg)) {
        return super.equals(obj);
      }
      CMsgReg other = (CMsgReg) obj;

      if (hasArea() != other.hasArea()) return false;
      if (hasArea()) {
        if (getArea()
            != other.getArea()) return false;
      }
      if (hasRegion() != other.hasRegion()) return false;
      if (hasRegion()) {
        if (getRegion()
            != other.getRegion()) return false;
      }
      if (hasShop() != other.hasShop()) return false;
      if (hasShop()) {
        if (getShop()
            != other.getShop()) return false;
      }
      if (hasRet() != other.hasRet()) return false;
      if (hasRet()) {
        if (getRet()
            != other.getRet()) return false;
      }
      if (hasTermid() != other.hasTermid()) return false;
      if (hasTermid()) {
        if (!getTermid()
            .equals(other.getTermid())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasArea()) {
        hash = (37 * hash) + AREA_FIELD_NUMBER;
        hash = (53 * hash) + getArea();
      }
      if (hasRegion()) {
        hash = (37 * hash) + REGION_FIELD_NUMBER;
        hash = (53 * hash) + getRegion();
      }
      if (hasShop()) {
        hash = (37 * hash) + SHOP_FIELD_NUMBER;
        hash = (53 * hash) + getShop();
      }
      if (hasRet()) {
        hash = (37 * hash) + RET_FIELD_NUMBER;
        hash = (53 * hash) + getRet();
      }
      if (hasTermid()) {
        hash = (37 * hash) + TERMID_FIELD_NUMBER;
        hash = (53 * hash) + getTermid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CMsgReg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsgReg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsgReg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsgReg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsgReg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CMsgReg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CMsgReg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CMsgReg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CMsgReg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CMsgReg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CMsgReg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CMsgReg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CMsgReg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code use_protobuf.blog1.CMsgReg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:use_protobuf.blog1.CMsgReg)
        CMsgRegOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_use_protobuf_blog1_CMsgReg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_use_protobuf_blog1_CMsgReg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CMsgReg.class, Builder.class);
      }

      // Construct using use_protobuf.blog1.Msg.CMsgReg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        area_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        region_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        shop_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        termid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_use_protobuf_blog1_CMsgReg_descriptor;
      }

      @Override
      public CMsgReg getDefaultInstanceForType() {
        return CMsgReg.getDefaultInstance();
      }

      @Override
      public CMsgReg build() {
        CMsgReg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CMsgReg buildPartial() {
        CMsgReg result = new CMsgReg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.area_ = area_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.region_ = region_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.shop_ = shop_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ret_ = ret_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.termid_ = termid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CMsgReg) {
          return mergeFrom((CMsgReg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CMsgReg other) {
        if (other == CMsgReg.getDefaultInstance()) return this;
        if (other.hasArea()) {
          setArea(other.getArea());
        }
        if (other.hasRegion()) {
          setRegion(other.getRegion());
        }
        if (other.hasShop()) {
          setShop(other.getShop());
        }
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasTermid()) {
          bitField0_ |= 0x00000010;
          termid_ = other.termid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CMsgReg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CMsgReg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int area_ ;
      /**
       * <code>optional int32 area = 1;</code>
       * @return Whether the area field is set.
       */
      public boolean hasArea() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 area = 1;</code>
       * @return The area.
       */
      public int getArea() {
        return area_;
      }
      /**
       * <code>optional int32 area = 1;</code>
       * @param value The area to set.
       * @return This builder for chaining.
       */
      public Builder setArea(int value) {
        bitField0_ |= 0x00000001;
        area_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 area = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearArea() {
        bitField0_ = (bitField0_ & ~0x00000001);
        area_ = 0;
        onChanged();
        return this;
      }

      private int region_ ;
      /**
       * <code>optional int32 region = 2;</code>
       * @return Whether the region field is set.
       */
      public boolean hasRegion() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 region = 2;</code>
       * @return The region.
       */
      public int getRegion() {
        return region_;
      }
      /**
       * <code>optional int32 region = 2;</code>
       * @param value The region to set.
       * @return This builder for chaining.
       */
      public Builder setRegion(int value) {
        bitField0_ |= 0x00000002;
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 region = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        region_ = 0;
        onChanged();
        return this;
      }

      private int shop_ ;
      /**
       * <code>optional int32 shop = 3;</code>
       * @return Whether the shop field is set.
       */
      public boolean hasShop() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 shop = 3;</code>
       * @return The shop.
       */
      public int getShop() {
        return shop_;
      }
      /**
       * <code>optional int32 shop = 3;</code>
       * @param value The shop to set.
       * @return This builder for chaining.
       */
      public Builder setShop(int value) {
        bitField0_ |= 0x00000004;
        shop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shop = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearShop() {
        bitField0_ = (bitField0_ & ~0x00000004);
        shop_ = 0;
        onChanged();
        return this;
      }

      private int ret_ ;
      /**
       * <code>optional int32 ret = 4;</code>
       * @return Whether the ret field is set.
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 ret = 4;</code>
       * @return The ret.
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>optional int32 ret = 4;</code>
       * @param value The ret to set.
       * @return This builder for chaining.
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000008;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ret = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ret_ = 0;
        onChanged();
        return this;
      }

      private Object termid_ = "";
      /**
       * <code>optional string termid = 5;</code>
       * @return Whether the termid field is set.
       */
      public boolean hasTermid() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string termid = 5;</code>
       * @return The termid.
       */
      public String getTermid() {
        Object ref = termid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            termid_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string termid = 5;</code>
       * @return The bytes for termid.
       */
      public com.google.protobuf.ByteString
          getTermidBytes() {
        Object ref = termid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          termid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string termid = 5;</code>
       * @param value The termid to set.
       * @return This builder for chaining.
       */
      public Builder setTermid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        termid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string termid = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTermid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        termid_ = getDefaultInstance().getTermid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string termid = 5;</code>
       * @param value The bytes for termid to set.
       * @return This builder for chaining.
       */
      public Builder setTermidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        termid_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:use_protobuf.blog1.CMsgReg)
    }

    // @@protoc_insertion_point(class_scope:use_protobuf.blog1.CMsgReg)
    private static final CMsgReg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CMsgReg();
    }

    public static CMsgReg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<CMsgReg>
        PARSER = new com.google.protobuf.AbstractParser<CMsgReg>() {
      @Override
      public CMsgReg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CMsgReg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CMsgReg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CMsgReg> getParserForType() {
      return PARSER;
    }

    @Override
    public CMsgReg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_blog1_CMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_blog1_CMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_blog1_CMsgHead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_blog1_CMsgHead_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_blog1_CMsgReg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_blog1_CMsgReg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tmsg.proto\022\022use_protobuf.blog1\"(\n\004CMsg\022" +
      "\017\n\007msghead\030\001 \002(\t\022\017\n\007msgbody\030\002 \002(\t\"p\n\010CMs" +
      "gHead\022\016\n\006msglen\030\001 \002(\005\022\017\n\007msgtype\030\002 \002(\005\022\016" +
      "\n\006msgseq\030\003 \002(\005\022\023\n\013termversion\030\004 \002(\005\022\016\n\006m" +
      "sgres\030\005 \002(\005\022\016\n\006termid\030\006 \002(\t\"R\n\007CMsgReg\022\014" +
      "\n\004area\030\001 \001(\005\022\016\n\006region\030\002 \001(\005\022\014\n\004shop\030\003 \001" +
      "(\005\022\013\n\003ret\030\004 \001(\005\022\016\n\006termid\030\005 \001(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_use_protobuf_blog1_CMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_use_protobuf_blog1_CMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_blog1_CMsg_descriptor,
        new String[] { "Msghead", "Msgbody", });
    internal_static_use_protobuf_blog1_CMsgHead_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_use_protobuf_blog1_CMsgHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_blog1_CMsgHead_descriptor,
        new String[] { "Msglen", "Msgtype", "Msgseq", "Termversion", "Msgres", "Termid", });
    internal_static_use_protobuf_blog1_CMsgReg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_use_protobuf_blog1_CMsgReg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_blog1_CMsgReg_descriptor,
        new String[] { "Area", "Region", "Shop", "Ret", "Termid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
