// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package use_protobuf.the_speed;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:use_protobuf.the_speed.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     * @return Whether the strObj field is set.
     */
    boolean hasStrObj();
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     * @return The strObj.
     */
    java.lang.String getStrObj();
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     * @return The bytes for strObj.
     */
    com.google.protobuf.ByteString
        getStrObjBytes();

    /**
     * <code>optional int32 int32Obj = 2;</code>
     * @return Whether the int32Obj field is set.
     */
    boolean hasInt32Obj();
    /**
     * <code>optional int32 int32Obj = 2;</code>
     * @return The int32Obj.
     */
    int getInt32Obj();

    /**
     * <code>optional int64 int64Obj = 3;</code>
     * @return Whether the int64Obj field is set.
     */
    boolean hasInt64Obj();
    /**
     * <code>optional int64 int64Obj = 3;</code>
     * @return The int64Obj.
     */
    long getInt64Obj();

    /**
     * <code>optional uint32 uint32Obj = 4;</code>
     * @return Whether the uint32Obj field is set.
     */
    boolean hasUint32Obj();
    /**
     * <code>optional uint32 uint32Obj = 4;</code>
     * @return The uint32Obj.
     */
    int getUint32Obj();

    /**
     * <code>optional uint64 uint64Obj = 5;</code>
     * @return Whether the uint64Obj field is set.
     */
    boolean hasUint64Obj();
    /**
     * <code>optional uint64 uint64Obj = 5;</code>
     * @return The uint64Obj.
     */
    long getUint64Obj();

    /**
     * <code>optional sint32 sint32Obj = 6;</code>
     * @return Whether the sint32Obj field is set.
     */
    boolean hasSint32Obj();
    /**
     * <code>optional sint32 sint32Obj = 6;</code>
     * @return The sint32Obj.
     */
    int getSint32Obj();

    /**
     * <code>optional sint64 sint64Obj = 7;</code>
     * @return Whether the sint64Obj field is set.
     */
    boolean hasSint64Obj();
    /**
     * <code>optional sint64 sint64Obj = 7;</code>
     * @return The sint64Obj.
     */
    long getSint64Obj();

    /**
     * <code>optional fixed32 fixed32Obj = 8;</code>
     * @return Whether the fixed32Obj field is set.
     */
    boolean hasFixed32Obj();
    /**
     * <code>optional fixed32 fixed32Obj = 8;</code>
     * @return The fixed32Obj.
     */
    int getFixed32Obj();

    /**
     * <code>optional fixed64 fixed64Obj = 9;</code>
     * @return Whether the fixed64Obj field is set.
     */
    boolean hasFixed64Obj();
    /**
     * <code>optional fixed64 fixed64Obj = 9;</code>
     * @return The fixed64Obj.
     */
    long getFixed64Obj();

    /**
     * <code>optional sfixed32 sfixed32Obj = 10;</code>
     * @return Whether the sfixed32Obj field is set.
     */
    boolean hasSfixed32Obj();
    /**
     * <code>optional sfixed32 sfixed32Obj = 10;</code>
     * @return The sfixed32Obj.
     */
    int getSfixed32Obj();

    /**
     * <code>optional sfixed64 sfixed64Obj = 11;</code>
     * @return Whether the sfixed64Obj field is set.
     */
    boolean hasSfixed64Obj();
    /**
     * <code>optional sfixed64 sfixed64Obj = 11;</code>
     * @return The sfixed64Obj.
     */
    long getSfixed64Obj();

    /**
     * <code>optional bool boolObj = 12;</code>
     * @return Whether the boolObj field is set.
     */
    boolean hasBoolObj();
    /**
     * <code>optional bool boolObj = 12;</code>
     * @return The boolObj.
     */
    boolean getBoolObj();

    /**
     * <code>optional bytes bytesObj = 13;</code>
     * @return Whether the bytesObj field is set.
     */
    boolean hasBytesObj();
    /**
     * <code>optional bytes bytesObj = 13;</code>
     * @return The bytesObj.
     */
    com.google.protobuf.ByteString getBytesObj();

    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     * @return Whether the folatObj field is set.
     */
    @java.lang.Deprecated boolean hasFolatObj();
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     * @return The folatObj.
     */
    @java.lang.Deprecated float getFolatObj();

    /**
     * <pre>
     *   
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     * @return A list containing the doubleObj.
     */
    java.util.List<java.lang.Double> getDoubleObjList();
    /**
     * <pre>
     *   
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     * @return The count of doubleObj.
     */
    int getDoubleObjCount();
    /**
     * <pre>
     *   
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The doubleObj at the given index.
     */
    double getDoubleObj(int index);

    /**
     * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
     * @return Whether the innerMessage field is set.
     */
    boolean hasInnerMessage();
    /**
     * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
     * @return The innerMessage.
     */
    use_protobuf.the_speed.InnerMessageProtos.InnerMessage getInnerMessage();
    /**
     * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
     */
    use_protobuf.the_speed.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder();
  }
  /**
   * Protobuf type {@code use_protobuf.the_speed.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:use_protobuf.the_speed.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      strObj_ = "hello";
      bytesObj_ = com.google.protobuf.ByteString.EMPTY;
      doubleObj_ = emptyDoubleList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              strObj_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              int32Obj_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              int64Obj_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              uint32Obj_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              uint64Obj_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sint32Obj_ = input.readSInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              sint64Obj_ = input.readSInt64();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              fixed32Obj_ = input.readFixed32();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              fixed64Obj_ = input.readFixed64();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              sfixed32Obj_ = input.readSFixed32();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000400;
              sfixed64Obj_ = input.readSFixed64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              boolObj_ = input.readBool();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              bytesObj_ = input.readBytes();
              break;
            }
            case 117: {
              bitField0_ |= 0x00002000;
              folatObj_ = input.readFloat();
              break;
            }
            case 121: {
              if (!((mutable_bitField0_ & 0x00004000) != 0)) {
                doubleObj_ = newDoubleList();
                mutable_bitField0_ |= 0x00004000;
              }
              doubleObj_.addDouble(input.readDouble());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00004000) != 0) && input.getBytesUntilLimit() > 0) {
                doubleObj_ = newDoubleList();
                mutable_bitField0_ |= 0x00004000;
              }
              while (input.getBytesUntilLimit() > 0) {
                doubleObj_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 130: {
              use_protobuf.the_speed.InnerMessageProtos.InnerMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00004000) != 0)) {
                subBuilder = innerMessage_.toBuilder();
              }
              innerMessage_ = input.readMessage(use_protobuf.the_speed.InnerMessageProtos.InnerMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(innerMessage_);
                innerMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00004000;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00004000) != 0)) {
          doubleObj_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return use_protobuf.the_speed.MessageProtos.internal_static_use_protobuf_the_speed_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return use_protobuf.the_speed.MessageProtos.internal_static_use_protobuf_the_speed_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              use_protobuf.the_speed.MessageProtos.Message.class, use_protobuf.the_speed.MessageProtos.Message.Builder.class);
    }

    private int bitField0_;
    public static final int STROBJ_FIELD_NUMBER = 1;
    private volatile java.lang.Object strObj_;
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     * @return Whether the strObj field is set.
     */
    public boolean hasStrObj() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     * @return The strObj.
     */
    public java.lang.String getStrObj() {
      java.lang.Object ref = strObj_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strObj_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     * @return The bytes for strObj.
     */
    public com.google.protobuf.ByteString
        getStrObjBytes() {
      java.lang.Object ref = strObj_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strObj_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INT32OBJ_FIELD_NUMBER = 2;
    private int int32Obj_;
    /**
     * <code>optional int32 int32Obj = 2;</code>
     * @return Whether the int32Obj field is set.
     */
    public boolean hasInt32Obj() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 int32Obj = 2;</code>
     * @return The int32Obj.
     */
    public int getInt32Obj() {
      return int32Obj_;
    }

    public static final int INT64OBJ_FIELD_NUMBER = 3;
    private long int64Obj_;
    /**
     * <code>optional int64 int64Obj = 3;</code>
     * @return Whether the int64Obj field is set.
     */
    public boolean hasInt64Obj() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 int64Obj = 3;</code>
     * @return The int64Obj.
     */
    public long getInt64Obj() {
      return int64Obj_;
    }

    public static final int UINT32OBJ_FIELD_NUMBER = 4;
    private int uint32Obj_;
    /**
     * <code>optional uint32 uint32Obj = 4;</code>
     * @return Whether the uint32Obj field is set.
     */
    public boolean hasUint32Obj() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 uint32Obj = 4;</code>
     * @return The uint32Obj.
     */
    public int getUint32Obj() {
      return uint32Obj_;
    }

    public static final int UINT64OBJ_FIELD_NUMBER = 5;
    private long uint64Obj_;
    /**
     * <code>optional uint64 uint64Obj = 5;</code>
     * @return Whether the uint64Obj field is set.
     */
    public boolean hasUint64Obj() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 uint64Obj = 5;</code>
     * @return The uint64Obj.
     */
    public long getUint64Obj() {
      return uint64Obj_;
    }

    public static final int SINT32OBJ_FIELD_NUMBER = 6;
    private int sint32Obj_;
    /**
     * <code>optional sint32 sint32Obj = 6;</code>
     * @return Whether the sint32Obj field is set.
     */
    public boolean hasSint32Obj() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional sint32 sint32Obj = 6;</code>
     * @return The sint32Obj.
     */
    public int getSint32Obj() {
      return sint32Obj_;
    }

    public static final int SINT64OBJ_FIELD_NUMBER = 7;
    private long sint64Obj_;
    /**
     * <code>optional sint64 sint64Obj = 7;</code>
     * @return Whether the sint64Obj field is set.
     */
    public boolean hasSint64Obj() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional sint64 sint64Obj = 7;</code>
     * @return The sint64Obj.
     */
    public long getSint64Obj() {
      return sint64Obj_;
    }

    public static final int FIXED32OBJ_FIELD_NUMBER = 8;
    private int fixed32Obj_;
    /**
     * <code>optional fixed32 fixed32Obj = 8;</code>
     * @return Whether the fixed32Obj field is set.
     */
    public boolean hasFixed32Obj() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional fixed32 fixed32Obj = 8;</code>
     * @return The fixed32Obj.
     */
    public int getFixed32Obj() {
      return fixed32Obj_;
    }

    public static final int FIXED64OBJ_FIELD_NUMBER = 9;
    private long fixed64Obj_;
    /**
     * <code>optional fixed64 fixed64Obj = 9;</code>
     * @return Whether the fixed64Obj field is set.
     */
    public boolean hasFixed64Obj() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional fixed64 fixed64Obj = 9;</code>
     * @return The fixed64Obj.
     */
    public long getFixed64Obj() {
      return fixed64Obj_;
    }

    public static final int SFIXED32OBJ_FIELD_NUMBER = 10;
    private int sfixed32Obj_;
    /**
     * <code>optional sfixed32 sfixed32Obj = 10;</code>
     * @return Whether the sfixed32Obj field is set.
     */
    public boolean hasSfixed32Obj() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional sfixed32 sfixed32Obj = 10;</code>
     * @return The sfixed32Obj.
     */
    public int getSfixed32Obj() {
      return sfixed32Obj_;
    }

    public static final int SFIXED64OBJ_FIELD_NUMBER = 11;
    private long sfixed64Obj_;
    /**
     * <code>optional sfixed64 sfixed64Obj = 11;</code>
     * @return Whether the sfixed64Obj field is set.
     */
    public boolean hasSfixed64Obj() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional sfixed64 sfixed64Obj = 11;</code>
     * @return The sfixed64Obj.
     */
    public long getSfixed64Obj() {
      return sfixed64Obj_;
    }

    public static final int BOOLOBJ_FIELD_NUMBER = 12;
    private boolean boolObj_;
    /**
     * <code>optional bool boolObj = 12;</code>
     * @return Whether the boolObj field is set.
     */
    public boolean hasBoolObj() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional bool boolObj = 12;</code>
     * @return The boolObj.
     */
    public boolean getBoolObj() {
      return boolObj_;
    }

    public static final int BYTESOBJ_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString bytesObj_;
    /**
     * <code>optional bytes bytesObj = 13;</code>
     * @return Whether the bytesObj field is set.
     */
    public boolean hasBytesObj() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>optional bytes bytesObj = 13;</code>
     * @return The bytesObj.
     */
    public com.google.protobuf.ByteString getBytesObj() {
      return bytesObj_;
    }

    public static final int FOLATOBJ_FIELD_NUMBER = 14;
    private float folatObj_;
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     * @return Whether the folatObj field is set.
     */
    @java.lang.Deprecated public boolean hasFolatObj() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     * @return The folatObj.
     */
    @java.lang.Deprecated public float getFolatObj() {
      return folatObj_;
    }

    public static final int DOUBLEOBJ_FIELD_NUMBER = 15;
    private com.google.protobuf.Internal.DoubleList doubleObj_;
    /**
     * <pre>
     *   
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     * @return A list containing the doubleObj.
     */
    public java.util.List<java.lang.Double>
        getDoubleObjList() {
      return doubleObj_;
    }
    /**
     * <pre>
     *   
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     * @return The count of doubleObj.
     */
    public int getDoubleObjCount() {
      return doubleObj_.size();
    }
    /**
     * <pre>
     *   
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The doubleObj at the given index.
     */
    public double getDoubleObj(int index) {
      return doubleObj_.getDouble(index);
    }
    private int doubleObjMemoizedSerializedSize = -1;

    public static final int INNERMESSAGE_FIELD_NUMBER = 16;
    private use_protobuf.the_speed.InnerMessageProtos.InnerMessage innerMessage_;
    /**
     * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
     * @return Whether the innerMessage field is set.
     */
    public boolean hasInnerMessage() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
     * @return The innerMessage.
     */
    public use_protobuf.the_speed.InnerMessageProtos.InnerMessage getInnerMessage() {
      return innerMessage_ == null ? use_protobuf.the_speed.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
    }
    /**
     * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
     */
    public use_protobuf.the_speed.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder() {
      return innerMessage_ == null ? use_protobuf.the_speed.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStrObj()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, strObj_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, int32Obj_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, int64Obj_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, uint32Obj_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(5, uint64Obj_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeSInt32(6, sint32Obj_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeSInt64(7, sint64Obj_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeFixed32(8, fixed32Obj_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeFixed64(9, fixed64Obj_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeSFixed32(10, sfixed32Obj_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeSFixed64(11, sfixed64Obj_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeBool(12, boolObj_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        output.writeBytes(13, bytesObj_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        output.writeFloat(14, folatObj_);
      }
      if (getDoubleObjList().size() > 0) {
        output.writeUInt32NoTag(122);
        output.writeUInt32NoTag(doubleObjMemoizedSerializedSize);
      }
      for (int i = 0; i < doubleObj_.size(); i++) {
        output.writeDoubleNoTag(doubleObj_.getDouble(i));
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        output.writeMessage(16, getInnerMessage());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, strObj_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, int32Obj_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, int64Obj_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, uint32Obj_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, uint64Obj_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, sint32Obj_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(7, sint64Obj_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(8, fixed32Obj_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(9, fixed64Obj_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(10, sfixed32Obj_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(11, sfixed64Obj_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, boolObj_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, bytesObj_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, folatObj_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDoubleObjList().size();
        size += dataSize;
        if (!getDoubleObjList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        doubleObjMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, getInnerMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof use_protobuf.the_speed.MessageProtos.Message)) {
        return super.equals(obj);
      }
      use_protobuf.the_speed.MessageProtos.Message other = (use_protobuf.the_speed.MessageProtos.Message) obj;

      if (hasStrObj() != other.hasStrObj()) return false;
      if (hasStrObj()) {
        if (!getStrObj()
            .equals(other.getStrObj())) return false;
      }
      if (hasInt32Obj() != other.hasInt32Obj()) return false;
      if (hasInt32Obj()) {
        if (getInt32Obj()
            != other.getInt32Obj()) return false;
      }
      if (hasInt64Obj() != other.hasInt64Obj()) return false;
      if (hasInt64Obj()) {
        if (getInt64Obj()
            != other.getInt64Obj()) return false;
      }
      if (hasUint32Obj() != other.hasUint32Obj()) return false;
      if (hasUint32Obj()) {
        if (getUint32Obj()
            != other.getUint32Obj()) return false;
      }
      if (hasUint64Obj() != other.hasUint64Obj()) return false;
      if (hasUint64Obj()) {
        if (getUint64Obj()
            != other.getUint64Obj()) return false;
      }
      if (hasSint32Obj() != other.hasSint32Obj()) return false;
      if (hasSint32Obj()) {
        if (getSint32Obj()
            != other.getSint32Obj()) return false;
      }
      if (hasSint64Obj() != other.hasSint64Obj()) return false;
      if (hasSint64Obj()) {
        if (getSint64Obj()
            != other.getSint64Obj()) return false;
      }
      if (hasFixed32Obj() != other.hasFixed32Obj()) return false;
      if (hasFixed32Obj()) {
        if (getFixed32Obj()
            != other.getFixed32Obj()) return false;
      }
      if (hasFixed64Obj() != other.hasFixed64Obj()) return false;
      if (hasFixed64Obj()) {
        if (getFixed64Obj()
            != other.getFixed64Obj()) return false;
      }
      if (hasSfixed32Obj() != other.hasSfixed32Obj()) return false;
      if (hasSfixed32Obj()) {
        if (getSfixed32Obj()
            != other.getSfixed32Obj()) return false;
      }
      if (hasSfixed64Obj() != other.hasSfixed64Obj()) return false;
      if (hasSfixed64Obj()) {
        if (getSfixed64Obj()
            != other.getSfixed64Obj()) return false;
      }
      if (hasBoolObj() != other.hasBoolObj()) return false;
      if (hasBoolObj()) {
        if (getBoolObj()
            != other.getBoolObj()) return false;
      }
      if (hasBytesObj() != other.hasBytesObj()) return false;
      if (hasBytesObj()) {
        if (!getBytesObj()
            .equals(other.getBytesObj())) return false;
      }
      if (hasFolatObj() != other.hasFolatObj()) return false;
      if (hasFolatObj()) {
        if (java.lang.Float.floatToIntBits(getFolatObj())
            != java.lang.Float.floatToIntBits(
                other.getFolatObj())) return false;
      }
      if (!getDoubleObjList()
          .equals(other.getDoubleObjList())) return false;
      if (hasInnerMessage() != other.hasInnerMessage()) return false;
      if (hasInnerMessage()) {
        if (!getInnerMessage()
            .equals(other.getInnerMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStrObj()) {
        hash = (37 * hash) + STROBJ_FIELD_NUMBER;
        hash = (53 * hash) + getStrObj().hashCode();
      }
      if (hasInt32Obj()) {
        hash = (37 * hash) + INT32OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getInt32Obj();
      }
      if (hasInt64Obj()) {
        hash = (37 * hash) + INT64OBJ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInt64Obj());
      }
      if (hasUint32Obj()) {
        hash = (37 * hash) + UINT32OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getUint32Obj();
      }
      if (hasUint64Obj()) {
        hash = (37 * hash) + UINT64OBJ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUint64Obj());
      }
      if (hasSint32Obj()) {
        hash = (37 * hash) + SINT32OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getSint32Obj();
      }
      if (hasSint64Obj()) {
        hash = (37 * hash) + SINT64OBJ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSint64Obj());
      }
      if (hasFixed32Obj()) {
        hash = (37 * hash) + FIXED32OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getFixed32Obj();
      }
      if (hasFixed64Obj()) {
        hash = (37 * hash) + FIXED64OBJ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFixed64Obj());
      }
      if (hasSfixed32Obj()) {
        hash = (37 * hash) + SFIXED32OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getSfixed32Obj();
      }
      if (hasSfixed64Obj()) {
        hash = (37 * hash) + SFIXED64OBJ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSfixed64Obj());
      }
      if (hasBoolObj()) {
        hash = (37 * hash) + BOOLOBJ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolObj());
      }
      if (hasBytesObj()) {
        hash = (37 * hash) + BYTESOBJ_FIELD_NUMBER;
        hash = (53 * hash) + getBytesObj().hashCode();
      }
      if (hasFolatObj()) {
        hash = (37 * hash) + FOLATOBJ_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFolatObj());
      }
      if (getDoubleObjCount() > 0) {
        hash = (37 * hash) + DOUBLEOBJ_FIELD_NUMBER;
        hash = (53 * hash) + getDoubleObjList().hashCode();
      }
      if (hasInnerMessage()) {
        hash = (37 * hash) + INNERMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getInnerMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static use_protobuf.the_speed.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(use_protobuf.the_speed.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code use_protobuf.the_speed.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:use_protobuf.the_speed.Message)
        use_protobuf.the_speed.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return use_protobuf.the_speed.MessageProtos.internal_static_use_protobuf_the_speed_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return use_protobuf.the_speed.MessageProtos.internal_static_use_protobuf_the_speed_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                use_protobuf.the_speed.MessageProtos.Message.class, use_protobuf.the_speed.MessageProtos.Message.Builder.class);
      }

      // Construct using use_protobuf.the_speed.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInnerMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        strObj_ = "hello";
        bitField0_ = (bitField0_ & ~0x00000001);
        int32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        int64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        uint32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        uint64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        sint32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        sint64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        fixed32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        fixed64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        sfixed32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        sfixed64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        boolObj_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        bytesObj_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        folatObj_ = 0F;
        bitField0_ = (bitField0_ & ~0x00002000);
        doubleObj_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00004000);
        if (innerMessageBuilder_ == null) {
          innerMessage_ = null;
        } else {
          innerMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return use_protobuf.the_speed.MessageProtos.internal_static_use_protobuf_the_speed_Message_descriptor;
      }

      @java.lang.Override
      public use_protobuf.the_speed.MessageProtos.Message getDefaultInstanceForType() {
        return use_protobuf.the_speed.MessageProtos.Message.getDefaultInstance();
      }

      @java.lang.Override
      public use_protobuf.the_speed.MessageProtos.Message build() {
        use_protobuf.the_speed.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public use_protobuf.the_speed.MessageProtos.Message buildPartial() {
        use_protobuf.the_speed.MessageProtos.Message result = new use_protobuf.the_speed.MessageProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.strObj_ = strObj_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.int32Obj_ = int32Obj_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.int64Obj_ = int64Obj_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.uint32Obj_ = uint32Obj_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.uint64Obj_ = uint64Obj_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.sint32Obj_ = sint32Obj_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.sint64Obj_ = sint64Obj_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.fixed32Obj_ = fixed32Obj_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.fixed64Obj_ = fixed64Obj_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.sfixed32Obj_ = sfixed32Obj_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.sfixed64Obj_ = sfixed64Obj_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.boolObj_ = boolObj_;
          to_bitField0_ |= 0x00000800;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          to_bitField0_ |= 0x00001000;
        }
        result.bytesObj_ = bytesObj_;
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.folatObj_ = folatObj_;
          to_bitField0_ |= 0x00002000;
        }
        if (((bitField0_ & 0x00004000) != 0)) {
          doubleObj_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.doubleObj_ = doubleObj_;
        if (((from_bitField0_ & 0x00008000) != 0)) {
          if (innerMessageBuilder_ == null) {
            result.innerMessage_ = innerMessage_;
          } else {
            result.innerMessage_ = innerMessageBuilder_.build();
          }
          to_bitField0_ |= 0x00004000;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof use_protobuf.the_speed.MessageProtos.Message) {
          return mergeFrom((use_protobuf.the_speed.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(use_protobuf.the_speed.MessageProtos.Message other) {
        if (other == use_protobuf.the_speed.MessageProtos.Message.getDefaultInstance()) return this;
        if (other.hasStrObj()) {
          bitField0_ |= 0x00000001;
          strObj_ = other.strObj_;
          onChanged();
        }
        if (other.hasInt32Obj()) {
          setInt32Obj(other.getInt32Obj());
        }
        if (other.hasInt64Obj()) {
          setInt64Obj(other.getInt64Obj());
        }
        if (other.hasUint32Obj()) {
          setUint32Obj(other.getUint32Obj());
        }
        if (other.hasUint64Obj()) {
          setUint64Obj(other.getUint64Obj());
        }
        if (other.hasSint32Obj()) {
          setSint32Obj(other.getSint32Obj());
        }
        if (other.hasSint64Obj()) {
          setSint64Obj(other.getSint64Obj());
        }
        if (other.hasFixed32Obj()) {
          setFixed32Obj(other.getFixed32Obj());
        }
        if (other.hasFixed64Obj()) {
          setFixed64Obj(other.getFixed64Obj());
        }
        if (other.hasSfixed32Obj()) {
          setSfixed32Obj(other.getSfixed32Obj());
        }
        if (other.hasSfixed64Obj()) {
          setSfixed64Obj(other.getSfixed64Obj());
        }
        if (other.hasBoolObj()) {
          setBoolObj(other.getBoolObj());
        }
        if (other.hasBytesObj()) {
          setBytesObj(other.getBytesObj());
        }
        if (other.hasFolatObj()) {
          setFolatObj(other.getFolatObj());
        }
        if (!other.doubleObj_.isEmpty()) {
          if (doubleObj_.isEmpty()) {
            doubleObj_ = other.doubleObj_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureDoubleObjIsMutable();
            doubleObj_.addAll(other.doubleObj_);
          }
          onChanged();
        }
        if (other.hasInnerMessage()) {
          mergeInnerMessage(other.getInnerMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStrObj()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        use_protobuf.the_speed.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (use_protobuf.the_speed.MessageProtos.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object strObj_ = "hello";
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       * @return Whether the strObj field is set.
       */
      public boolean hasStrObj() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       * @return The strObj.
       */
      public java.lang.String getStrObj() {
        java.lang.Object ref = strObj_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            strObj_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       * @return The bytes for strObj.
       */
      public com.google.protobuf.ByteString
          getStrObjBytes() {
        java.lang.Object ref = strObj_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strObj_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       * @param value The strObj to set.
       * @return This builder for chaining.
       */
      public Builder setStrObj(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStrObj() {
        bitField0_ = (bitField0_ & ~0x00000001);
        strObj_ = getDefaultInstance().getStrObj();
        onChanged();
        return this;
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       * @param value The bytes for strObj to set.
       * @return This builder for chaining.
       */
      public Builder setStrObjBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strObj_ = value;
        onChanged();
        return this;
      }

      private int int32Obj_ ;
      /**
       * <code>optional int32 int32Obj = 2;</code>
       * @return Whether the int32Obj field is set.
       */
      public boolean hasInt32Obj() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       * @return The int32Obj.
       */
      public int getInt32Obj() {
        return int32Obj_;
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       * @param value The int32Obj to set.
       * @return This builder for chaining.
       */
      public Builder setInt32Obj(int value) {
        bitField0_ |= 0x00000002;
        int32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInt32Obj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        int32Obj_ = 0;
        onChanged();
        return this;
      }

      private long int64Obj_ ;
      /**
       * <code>optional int64 int64Obj = 3;</code>
       * @return Whether the int64Obj field is set.
       */
      public boolean hasInt64Obj() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       * @return The int64Obj.
       */
      public long getInt64Obj() {
        return int64Obj_;
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       * @param value The int64Obj to set.
       * @return This builder for chaining.
       */
      public Builder setInt64Obj(long value) {
        bitField0_ |= 0x00000004;
        int64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInt64Obj() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int uint32Obj_ ;
      /**
       * <code>optional uint32 uint32Obj = 4;</code>
       * @return Whether the uint32Obj field is set.
       */
      public boolean hasUint32Obj() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 uint32Obj = 4;</code>
       * @return The uint32Obj.
       */
      public int getUint32Obj() {
        return uint32Obj_;
      }
      /**
       * <code>optional uint32 uint32Obj = 4;</code>
       * @param value The uint32Obj to set.
       * @return This builder for chaining.
       */
      public Builder setUint32Obj(int value) {
        bitField0_ |= 0x00000008;
        uint32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uint32Obj = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUint32Obj() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uint32Obj_ = 0;
        onChanged();
        return this;
      }

      private long uint64Obj_ ;
      /**
       * <code>optional uint64 uint64Obj = 5;</code>
       * @return Whether the uint64Obj field is set.
       */
      public boolean hasUint64Obj() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint64 uint64Obj = 5;</code>
       * @return The uint64Obj.
       */
      public long getUint64Obj() {
        return uint64Obj_;
      }
      /**
       * <code>optional uint64 uint64Obj = 5;</code>
       * @param value The uint64Obj to set.
       * @return This builder for chaining.
       */
      public Builder setUint64Obj(long value) {
        bitField0_ |= 0x00000010;
        uint64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 uint64Obj = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUint64Obj() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uint64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int sint32Obj_ ;
      /**
       * <code>optional sint32 sint32Obj = 6;</code>
       * @return Whether the sint32Obj field is set.
       */
      public boolean hasSint32Obj() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional sint32 sint32Obj = 6;</code>
       * @return The sint32Obj.
       */
      public int getSint32Obj() {
        return sint32Obj_;
      }
      /**
       * <code>optional sint32 sint32Obj = 6;</code>
       * @param value The sint32Obj to set.
       * @return This builder for chaining.
       */
      public Builder setSint32Obj(int value) {
        bitField0_ |= 0x00000020;
        sint32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 sint32Obj = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSint32Obj() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sint32Obj_ = 0;
        onChanged();
        return this;
      }

      private long sint64Obj_ ;
      /**
       * <code>optional sint64 sint64Obj = 7;</code>
       * @return Whether the sint64Obj field is set.
       */
      public boolean hasSint64Obj() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional sint64 sint64Obj = 7;</code>
       * @return The sint64Obj.
       */
      public long getSint64Obj() {
        return sint64Obj_;
      }
      /**
       * <code>optional sint64 sint64Obj = 7;</code>
       * @param value The sint64Obj to set.
       * @return This builder for chaining.
       */
      public Builder setSint64Obj(long value) {
        bitField0_ |= 0x00000040;
        sint64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 sint64Obj = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSint64Obj() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sint64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int fixed32Obj_ ;
      /**
       * <code>optional fixed32 fixed32Obj = 8;</code>
       * @return Whether the fixed32Obj field is set.
       */
      public boolean hasFixed32Obj() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional fixed32 fixed32Obj = 8;</code>
       * @return The fixed32Obj.
       */
      public int getFixed32Obj() {
        return fixed32Obj_;
      }
      /**
       * <code>optional fixed32 fixed32Obj = 8;</code>
       * @param value The fixed32Obj to set.
       * @return This builder for chaining.
       */
      public Builder setFixed32Obj(int value) {
        bitField0_ |= 0x00000080;
        fixed32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 fixed32Obj = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFixed32Obj() {
        bitField0_ = (bitField0_ & ~0x00000080);
        fixed32Obj_ = 0;
        onChanged();
        return this;
      }

      private long fixed64Obj_ ;
      /**
       * <code>optional fixed64 fixed64Obj = 9;</code>
       * @return Whether the fixed64Obj field is set.
       */
      public boolean hasFixed64Obj() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional fixed64 fixed64Obj = 9;</code>
       * @return The fixed64Obj.
       */
      public long getFixed64Obj() {
        return fixed64Obj_;
      }
      /**
       * <code>optional fixed64 fixed64Obj = 9;</code>
       * @param value The fixed64Obj to set.
       * @return This builder for chaining.
       */
      public Builder setFixed64Obj(long value) {
        bitField0_ |= 0x00000100;
        fixed64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 fixed64Obj = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearFixed64Obj() {
        bitField0_ = (bitField0_ & ~0x00000100);
        fixed64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int sfixed32Obj_ ;
      /**
       * <code>optional sfixed32 sfixed32Obj = 10;</code>
       * @return Whether the sfixed32Obj field is set.
       */
      public boolean hasSfixed32Obj() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional sfixed32 sfixed32Obj = 10;</code>
       * @return The sfixed32Obj.
       */
      public int getSfixed32Obj() {
        return sfixed32Obj_;
      }
      /**
       * <code>optional sfixed32 sfixed32Obj = 10;</code>
       * @param value The sfixed32Obj to set.
       * @return This builder for chaining.
       */
      public Builder setSfixed32Obj(int value) {
        bitField0_ |= 0x00000200;
        sfixed32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed32 sfixed32Obj = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSfixed32Obj() {
        bitField0_ = (bitField0_ & ~0x00000200);
        sfixed32Obj_ = 0;
        onChanged();
        return this;
      }

      private long sfixed64Obj_ ;
      /**
       * <code>optional sfixed64 sfixed64Obj = 11;</code>
       * @return Whether the sfixed64Obj field is set.
       */
      public boolean hasSfixed64Obj() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional sfixed64 sfixed64Obj = 11;</code>
       * @return The sfixed64Obj.
       */
      public long getSfixed64Obj() {
        return sfixed64Obj_;
      }
      /**
       * <code>optional sfixed64 sfixed64Obj = 11;</code>
       * @param value The sfixed64Obj to set.
       * @return This builder for chaining.
       */
      public Builder setSfixed64Obj(long value) {
        bitField0_ |= 0x00000400;
        sfixed64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed64 sfixed64Obj = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearSfixed64Obj() {
        bitField0_ = (bitField0_ & ~0x00000400);
        sfixed64Obj_ = 0L;
        onChanged();
        return this;
      }

      private boolean boolObj_ ;
      /**
       * <code>optional bool boolObj = 12;</code>
       * @return Whether the boolObj field is set.
       */
      public boolean hasBoolObj() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       * @return The boolObj.
       */
      public boolean getBoolObj() {
        return boolObj_;
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       * @param value The boolObj to set.
       * @return This builder for chaining.
       */
      public Builder setBoolObj(boolean value) {
        bitField0_ |= 0x00000800;
        boolObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolObj() {
        bitField0_ = (bitField0_ & ~0x00000800);
        boolObj_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesObj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes bytesObj = 13;</code>
       * @return Whether the bytesObj field is set.
       */
      public boolean hasBytesObj() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       * @return The bytesObj.
       */
      public com.google.protobuf.ByteString getBytesObj() {
        return bytesObj_;
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       * @param value The bytesObj to set.
       * @return This builder for chaining.
       */
      public Builder setBytesObj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        bytesObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytesObj() {
        bitField0_ = (bitField0_ & ~0x00001000);
        bytesObj_ = getDefaultInstance().getBytesObj();
        onChanged();
        return this;
      }

      private float folatObj_ ;
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       * @return Whether the folatObj field is set.
       */
      @java.lang.Deprecated public boolean hasFolatObj() {
        return ((bitField0_ & 0x00002000) != 0);
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       * @return The folatObj.
       */
      @java.lang.Deprecated public float getFolatObj() {
        return folatObj_;
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       * @param value The folatObj to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setFolatObj(float value) {
        bitField0_ |= 0x00002000;
        folatObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearFolatObj() {
        bitField0_ = (bitField0_ & ~0x00002000);
        folatObj_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList doubleObj_ = emptyDoubleList();
      private void ensureDoubleObjIsMutable() {
        if (!((bitField0_ & 0x00004000) != 0)) {
          doubleObj_ = mutableCopy(doubleObj_);
          bitField0_ |= 0x00004000;
         }
      }
      /**
       * <pre>
       *   
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       * @return A list containing the doubleObj.
       */
      public java.util.List<java.lang.Double>
          getDoubleObjList() {
        return ((bitField0_ & 0x00004000) != 0) ?
                 java.util.Collections.unmodifiableList(doubleObj_) : doubleObj_;
      }
      /**
       * <pre>
       *   
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       * @return The count of doubleObj.
       */
      public int getDoubleObjCount() {
        return doubleObj_.size();
      }
      /**
       * <pre>
       *   
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       * @param index The index of the element to return.
       * @return The doubleObj at the given index.
       */
      public double getDoubleObj(int index) {
        return doubleObj_.getDouble(index);
      }
      /**
       * <pre>
       *   
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       * @param index The index to set the value at.
       * @param value The doubleObj to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleObj(
          int index, double value) {
        ensureDoubleObjIsMutable();
        doubleObj_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       * @param value The doubleObj to add.
       * @return This builder for chaining.
       */
      public Builder addDoubleObj(double value) {
        ensureDoubleObjIsMutable();
        doubleObj_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       * @param values The doubleObj to add.
       * @return This builder for chaining.
       */
      public Builder addAllDoubleObj(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDoubleObjIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, doubleObj_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleObj() {
        doubleObj_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }

      private use_protobuf.the_speed.InnerMessageProtos.InnerMessage innerMessage_;
      private com.google.protobuf.SingleFieldBuilderV3<
          use_protobuf.the_speed.InnerMessageProtos.InnerMessage, use_protobuf.the_speed.InnerMessageProtos.InnerMessage.Builder, use_protobuf.the_speed.InnerMessageProtos.InnerMessageOrBuilder> innerMessageBuilder_;
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       * @return Whether the innerMessage field is set.
       */
      public boolean hasInnerMessage() {
        return ((bitField0_ & 0x00008000) != 0);
      }
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       * @return The innerMessage.
       */
      public use_protobuf.the_speed.InnerMessageProtos.InnerMessage getInnerMessage() {
        if (innerMessageBuilder_ == null) {
          return innerMessage_ == null ? use_protobuf.the_speed.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
        } else {
          return innerMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       */
      public Builder setInnerMessage(use_protobuf.the_speed.InnerMessageProtos.InnerMessage value) {
        if (innerMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerMessage_ = value;
          onChanged();
        } else {
          innerMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       */
      public Builder setInnerMessage(
          use_protobuf.the_speed.InnerMessageProtos.InnerMessage.Builder builderForValue) {
        if (innerMessageBuilder_ == null) {
          innerMessage_ = builderForValue.build();
          onChanged();
        } else {
          innerMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       */
      public Builder mergeInnerMessage(use_protobuf.the_speed.InnerMessageProtos.InnerMessage value) {
        if (innerMessageBuilder_ == null) {
          if (((bitField0_ & 0x00008000) != 0) &&
              innerMessage_ != null &&
              innerMessage_ != use_protobuf.the_speed.InnerMessageProtos.InnerMessage.getDefaultInstance()) {
            innerMessage_ =
              use_protobuf.the_speed.InnerMessageProtos.InnerMessage.newBuilder(innerMessage_).mergeFrom(value).buildPartial();
          } else {
            innerMessage_ = value;
          }
          onChanged();
        } else {
          innerMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       */
      public Builder clearInnerMessage() {
        if (innerMessageBuilder_ == null) {
          innerMessage_ = null;
          onChanged();
        } else {
          innerMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       */
      public use_protobuf.the_speed.InnerMessageProtos.InnerMessage.Builder getInnerMessageBuilder() {
        bitField0_ |= 0x00008000;
        onChanged();
        return getInnerMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       */
      public use_protobuf.the_speed.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder() {
        if (innerMessageBuilder_ != null) {
          return innerMessageBuilder_.getMessageOrBuilder();
        } else {
          return innerMessage_ == null ?
              use_protobuf.the_speed.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
        }
      }
      /**
       * <code>optional .use_protobuf.the_speed.InnerMessage innerMessage = 16;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          use_protobuf.the_speed.InnerMessageProtos.InnerMessage, use_protobuf.the_speed.InnerMessageProtos.InnerMessage.Builder, use_protobuf.the_speed.InnerMessageProtos.InnerMessageOrBuilder> 
          getInnerMessageFieldBuilder() {
        if (innerMessageBuilder_ == null) {
          innerMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              use_protobuf.the_speed.InnerMessageProtos.InnerMessage, use_protobuf.the_speed.InnerMessageProtos.InnerMessage.Builder, use_protobuf.the_speed.InnerMessageProtos.InnerMessageOrBuilder>(
                  getInnerMessage(),
                  getParentForChildren(),
                  isClean());
          innerMessage_ = null;
        }
        return innerMessageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:use_protobuf.the_speed.Message)
    }

    // @@protoc_insertion_point(class_scope:use_protobuf.the_speed.Message)
    private static final use_protobuf.the_speed.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new use_protobuf.the_speed.MessageProtos.Message();
    }

    public static use_protobuf.the_speed.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public use_protobuf.the_speed.MessageProtos.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_the_speed_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_the_speed_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\026use_protobuf.the_speed\032" +
      "\022InnerMessage.proto\"\356\002\n\007Message\022\025\n\006strOb" +
      "j\030\001 \002(\t:\005hello\022\020\n\010int32Obj\030\002 \001(\005\022\020\n\010int6" +
      "4Obj\030\003 \001(\003\022\021\n\tuint32Obj\030\004 \001(\r\022\021\n\tuint64O" +
      "bj\030\005 \001(\004\022\021\n\tsint32Obj\030\006 \001(\021\022\021\n\tsint64Obj" +
      "\030\007 \001(\022\022\022\n\nfixed32Obj\030\010 \001(\007\022\022\n\nfixed64Obj" +
      "\030\t \001(\006\022\023\n\013sfixed32Obj\030\n \001(\017\022\023\n\013sfixed64O" +
      "bj\030\013 \001(\020\022\017\n\007boolObj\030\014 \001(\010\022\020\n\010bytesObj\030\r " +
      "\001(\014\022\024\n\010folatObj\030\016 \001(\002B\002\030\001\022\025\n\tdoubleObj\030\017" +
      " \003(\001B\002\020\001\022:\n\014innerMessage\030\020 \001(\0132$.use_pro" +
      "tobuf.the_speed.InnerMessageB\024B\rMessageP" +
      "rotosH\001\210\001\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          use_protobuf.the_speed.InnerMessageProtos.getDescriptor(),
        });
    internal_static_use_protobuf_the_speed_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_use_protobuf_the_speed_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_the_speed_Message_descriptor,
        new java.lang.String[] { "StrObj", "Int32Obj", "Int64Obj", "Uint32Obj", "Uint64Obj", "Sint32Obj", "Sint64Obj", "Fixed32Obj", "Fixed64Obj", "Sfixed32Obj", "Sfixed64Obj", "BoolObj", "BytesObj", "FolatObj", "DoubleObj", "InnerMessage", });
    use_protobuf.the_speed.InnerMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
