// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package use_protobuf.blog2;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AOrBuilder extends
      // @@protoc_insertion_point(interface_extends:use_protobuf.blog2.A)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string a = 1;</code>
     * @return Whether the a field is set.
     */
    boolean hasA();
    /**
     * <code>required string a = 1;</code>
     * @return The a.
     */
    String getA();
    /**
     * <code>required string a = 1;</code>
     * @return The bytes for a.
     */
    com.google.protobuf.ByteString
        getABytes();

    /**
     * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
     * @return Whether the b1 field is set.
     */
    boolean hasB1();
    /**
     * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
     * @return The b1.
     */
    A.B1 getB1();
    /**
     * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
     */
    A.B1OrBuilder getB1OrBuilder();

    /**
     * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
     * @return Whether the b2 field is set.
     */
    boolean hasB2();
    /**
     * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
     * @return The b2.
     */
    A.B2 getB2();
    /**
     * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
     */
    A.B2OrBuilder getB2OrBuilder();

    /**
     * <code>optional int32 num = 4;</code>
     * @return Whether the num field is set.
     */
    boolean hasNum();
    /**
     * <code>optional int32 num = 4;</code>
     * @return The num.
     */
    int getNum();
  }
  /**
   * Protobuf type {@code use_protobuf.blog2.A}
   */
  public  static final class A extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:use_protobuf.blog2.A)
      AOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use A.newBuilder() to construct.
    private A(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private A() {
      a_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new A();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private A(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              a_ = bs;
              break;
            }
            case 18: {
              B1.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = b1_.toBuilder();
              }
              b1_ = input.readMessage(B1.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(b1_);
                b1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              B2.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = b2_.toBuilder();
              }
              b2_ = input.readMessage(B2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(b2_);
                b2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              num_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Test.internal_static_use_protobuf_blog2_A_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Test.internal_static_use_protobuf_blog2_A_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              A.class, Builder.class);
    }

    public interface B1OrBuilder extends
        // @@protoc_insertion_point(interface_extends:use_protobuf.blog2.A.B1)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string b = 1;</code>
       * @return Whether the b field is set.
       */
      boolean hasB();
      /**
       * <code>optional string b = 1;</code>
       * @return The b.
       */
      String getB();
      /**
       * <code>optional string b = 1;</code>
       * @return The bytes for b.
       */
      com.google.protobuf.ByteString
          getBBytes();

      /**
       * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
       * @return Whether the c field is set.
       */
      boolean hasC();
      /**
       * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
       * @return The c.
       */
      B1.C getC();
      /**
       * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
       */
      B1.COrBuilder getCOrBuilder();
    }
    /**
     * Protobuf type {@code use_protobuf.blog2.A.B1}
     */
    public  static final class B1 extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:use_protobuf.blog2.A.B1)
        B1OrBuilder {
    private static final long serialVersionUID = 0L;
      // Use B1.newBuilder() to construct.
      private B1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private B1() {
        b_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new B1();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private B1(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                b_ = bs;
                break;
              }
              case 18: {
                C.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) != 0)) {
                  subBuilder = c_.toBuilder();
                }
                c_ = input.readMessage(C.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(c_);
                  c_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test.internal_static_use_protobuf_blog2_A_B1_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test.internal_static_use_protobuf_blog2_A_B1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                B1.class, Builder.class);
      }

      public interface COrBuilder extends
          // @@protoc_insertion_point(interface_extends:use_protobuf.blog2.A.B1.C)
          com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string c = 1;</code>
         * @return Whether the c field is set.
         */
        boolean hasC();
        /**
         * <code>optional string c = 1;</code>
         * @return The c.
         */
        String getC();
        /**
         * <code>optional string c = 1;</code>
         * @return The bytes for c.
         */
        com.google.protobuf.ByteString
            getCBytes();
      }
      /**
       * Protobuf type {@code use_protobuf.blog2.A.B1.C}
       */
      public  static final class C extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:use_protobuf.blog2.A.B1.C)
          COrBuilder {
      private static final long serialVersionUID = 0L;
        // Use C.newBuilder() to construct.
        private C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
          super(builder);
        }
        private C() {
          c_ = "";
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
            UnusedPrivateParameter unused) {
          return new C();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
          return this.unknownFields;
        }
        private C(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          this();
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  com.google.protobuf.ByteString bs = input.readBytes();
                  bitField0_ |= 0x00000001;
                  c_ = bs;
                  break;
                }
                default: {
                  if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Test.internal_static_use_protobuf_blog2_A_B1_C_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Test.internal_static_use_protobuf_blog2_A_B1_C_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  C.class, Builder.class);
        }

        private int bitField0_;
        public static final int C_FIELD_NUMBER = 1;
        private volatile Object c_;
        /**
         * <code>optional string c = 1;</code>
         * @return Whether the c field is set.
         */
        public boolean hasC() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string c = 1;</code>
         * @return The c.
         */
        public String getC() {
          Object ref = c_;
          if (ref instanceof String) {
            return (String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              c_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string c = 1;</code>
         * @return The bytes for c.
         */
        public com.google.protobuf.ByteString
            getCBytes() {
          Object ref = c_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            c_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        private byte memoizedIsInitialized = -1;
        @Override
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return true;
          if (isInitialized == 0) return false;

          memoizedIsInitialized = 1;
          return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          if (((bitField0_ & 0x00000001) != 0)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, c_);
          }
          unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
          int size = memoizedSize;
          if (size != -1) return size;

          size = 0;
          if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, c_);
          }
          size += unknownFields.getSerializedSize();
          memoizedSize = size;
          return size;
        }

        @Override
        public boolean equals(final Object obj) {
          if (obj == this) {
           return true;
          }
          if (!(obj instanceof C)) {
            return super.equals(obj);
          }
          C other = (C) obj;

          if (hasC() != other.hasC()) return false;
          if (hasC()) {
            if (!getC()
                .equals(other.getC())) return false;
          }
          if (!unknownFields.equals(other.unknownFields)) return false;
          return true;
        }

        @Override
        public int hashCode() {
          if (memoizedHashCode != 0) {
            return memoizedHashCode;
          }
          int hash = 41;
          hash = (19 * hash) + getDescriptor().hashCode();
          if (hasC()) {
            hash = (37 * hash) + C_FIELD_NUMBER;
            hash = (53 * hash) + getC().hashCode();
          }
          hash = (29 * hash) + unknownFields.hashCode();
          memoizedHashCode = hash;
          return hash;
        }

        public static C parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static C parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static C parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static C parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static C parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static C parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static C parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static C parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static C parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
        }
        public static C parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static C parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static C parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(C prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @Override
        public Builder toBuilder() {
          return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
            BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code use_protobuf.blog2.A.B1.C}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:use_protobuf.blog2.A.B1.C)
            COrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return Test.internal_static_use_protobuf_blog2_A_B1_C_descriptor;
          }

          @Override
          protected FieldAccessorTable
              internalGetFieldAccessorTable() {
            return Test.internal_static_use_protobuf_blog2_A_B1_C_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    C.class, Builder.class);
          }

          // Construct using use_protobuf.blog2.Test.A.B1.C.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
          }
          @Override
          public Builder clear() {
            super.clear();
            c_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
          }

          @Override
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return Test.internal_static_use_protobuf_blog2_A_B1_C_descriptor;
          }

          @Override
          public C getDefaultInstanceForType() {
            return C.getDefaultInstance();
          }

          @Override
          public C build() {
            C result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          @Override
          public C buildPartial() {
            C result = new C(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
              to_bitField0_ |= 0x00000001;
            }
            result.c_ = c_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }

          @Override
          public Builder clone() {
            return super.clone();
          }
          @Override
          public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
            return super.setField(field, value);
          }
          @Override
          public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
          }
          @Override
          public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
          }
          @Override
          public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
            return super.setRepeatedField(field, index, value);
          }
          @Override
          public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
            return super.addRepeatedField(field, value);
          }
          @Override
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof C) {
              return mergeFrom((C)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(C other) {
            if (other == C.getDefaultInstance()) return this;
            if (other.hasC()) {
              bitField0_ |= 0x00000001;
              c_ = other.c_;
              onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
          }

          @Override
          public final boolean isInitialized() {
            return true;
          }

          @Override
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            C parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (C) e.getUnfinishedMessage();
              throw e.unwrapIOException();
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          private Object c_ = "";
          /**
           * <code>optional string c = 1;</code>
           * @return Whether the c field is set.
           */
          public boolean hasC() {
            return ((bitField0_ & 0x00000001) != 0);
          }
          /**
           * <code>optional string c = 1;</code>
           * @return The c.
           */
          public String getC() {
            Object ref = c_;
            if (!(ref instanceof String)) {
              com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
              String s = bs.toStringUtf8();
              if (bs.isValidUtf8()) {
                c_ = s;
              }
              return s;
            } else {
              return (String) ref;
            }
          }
          /**
           * <code>optional string c = 1;</code>
           * @return The bytes for c.
           */
          public com.google.protobuf.ByteString
              getCBytes() {
            Object ref = c_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
              c_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string c = 1;</code>
           * @param value The c to set.
           * @return This builder for chaining.
           */
          public Builder setC(
              String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            c_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional string c = 1;</code>
           * @return This builder for chaining.
           */
          public Builder clearC() {
            bitField0_ = (bitField0_ & ~0x00000001);
            c_ = getDefaultInstance().getC();
            onChanged();
            return this;
          }
          /**
           * <code>optional string c = 1;</code>
           * @param value The bytes for c to set.
           * @return This builder for chaining.
           */
          public Builder setCBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            c_ = value;
            onChanged();
            return this;
          }
          @Override
          public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
          }

          @Override
          public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
          }


          // @@protoc_insertion_point(builder_scope:use_protobuf.blog2.A.B1.C)
        }

        // @@protoc_insertion_point(class_scope:use_protobuf.blog2.A.B1.C)
        private static final C DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new C();
        }

        public static C getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        @Deprecated public static final com.google.protobuf.Parser<C>
            PARSER = new com.google.protobuf.AbstractParser<C>() {
          @Override
          public C parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new C(input, extensionRegistry);
          }
        };

        public static com.google.protobuf.Parser<C> parser() {
          return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<C> getParserForType() {
          return PARSER;
        }

        @Override
        public C getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
        }

      }

      private int bitField0_;
      public static final int B_FIELD_NUMBER = 1;
      private volatile Object b_;
      /**
       * <code>optional string b = 1;</code>
       * @return Whether the b field is set.
       */
      public boolean hasB() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string b = 1;</code>
       * @return The b.
       */
      public String getB() {
        Object ref = b_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            b_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string b = 1;</code>
       * @return The bytes for b.
       */
      public com.google.protobuf.ByteString
          getBBytes() {
        Object ref = b_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int C_FIELD_NUMBER = 2;
      private C c_;
      /**
       * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
       * @return Whether the c field is set.
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
       * @return The c.
       */
      public C getC() {
        return c_ == null ? C.getDefaultInstance() : c_;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
       */
      public COrBuilder getCOrBuilder() {
        return c_ == null ? C.getDefaultInstance() : c_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, b_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeMessage(2, getC());
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, b_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getC());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof B1)) {
          return super.equals(obj);
        }
        B1 other = (B1) obj;

        if (hasB() != other.hasB()) return false;
        if (hasB()) {
          if (!getB()
              .equals(other.getB())) return false;
        }
        if (hasC() != other.hasC()) return false;
        if (hasC()) {
          if (!getC()
              .equals(other.getC())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasB()) {
          hash = (37 * hash) + B_FIELD_NUMBER;
          hash = (53 * hash) + getB().hashCode();
        }
        if (hasC()) {
          hash = (37 * hash) + C_FIELD_NUMBER;
          hash = (53 * hash) + getC().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static B1 parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static B1 parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static B1 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static B1 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static B1 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static B1 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static B1 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static B1 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static B1 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static B1 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static B1 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static B1 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(B1 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code use_protobuf.blog2.A.B1}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:use_protobuf.blog2.A.B1)
          B1OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Test.internal_static_use_protobuf_blog2_A_B1_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Test.internal_static_use_protobuf_blog2_A_B1_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  B1.class, Builder.class);
        }

        // Construct using use_protobuf.blog2.Test.A.B1.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getCFieldBuilder();
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          b_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          if (cBuilder_ == null) {
            c_ = null;
          } else {
            cBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Test.internal_static_use_protobuf_blog2_A_B1_descriptor;
        }

        @Override
        public B1 getDefaultInstanceForType() {
          return B1.getDefaultInstance();
        }

        @Override
        public B1 build() {
          B1 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public B1 buildPartial() {
          B1 result = new B1(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.b_ = b_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            if (cBuilder_ == null) {
              result.c_ = c_;
            } else {
              result.c_ = cBuilder_.build();
            }
            to_bitField0_ |= 0x00000002;
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof B1) {
            return mergeFrom((B1)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(B1 other) {
          if (other == B1.getDefaultInstance()) return this;
          if (other.hasB()) {
            bitField0_ |= 0x00000001;
            b_ = other.b_;
            onChanged();
          }
          if (other.hasC()) {
            mergeC(other.getC());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          B1 parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (B1) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private Object b_ = "";
        /**
         * <code>optional string b = 1;</code>
         * @return Whether the b field is set.
         */
        public boolean hasB() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string b = 1;</code>
         * @return The b.
         */
        public String getB() {
          Object ref = b_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              b_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string b = 1;</code>
         * @return The bytes for b.
         */
        public com.google.protobuf.ByteString
            getBBytes() {
          Object ref = b_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            b_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string b = 1;</code>
         * @param value The b to set.
         * @return This builder for chaining.
         */
        public Builder setB(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          b_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string b = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearB() {
          bitField0_ = (bitField0_ & ~0x00000001);
          b_ = getDefaultInstance().getB();
          onChanged();
          return this;
        }
        /**
         * <code>optional string b = 1;</code>
         * @param value The bytes for b to set.
         * @return This builder for chaining.
         */
        public Builder setBBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          b_ = value;
          onChanged();
          return this;
        }

        private C c_;
        private com.google.protobuf.SingleFieldBuilderV3<
            C, C.Builder, COrBuilder> cBuilder_;
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         * @return Whether the c field is set.
         */
        public boolean hasC() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         * @return The c.
         */
        public C getC() {
          if (cBuilder_ == null) {
            return c_ == null ? C.getDefaultInstance() : c_;
          } else {
            return cBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         */
        public Builder setC(C value) {
          if (cBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            c_ = value;
            onChanged();
          } else {
            cBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         */
        public Builder setC(
            C.Builder builderForValue) {
          if (cBuilder_ == null) {
            c_ = builderForValue.build();
            onChanged();
          } else {
            cBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         */
        public Builder mergeC(C value) {
          if (cBuilder_ == null) {
            if (((bitField0_ & 0x00000002) != 0) &&
                c_ != null &&
                c_ != C.getDefaultInstance()) {
              c_ =
                C.newBuilder(c_).mergeFrom(value).buildPartial();
            } else {
              c_ = value;
            }
            onChanged();
          } else {
            cBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         */
        public Builder clearC() {
          if (cBuilder_ == null) {
            c_ = null;
            onChanged();
          } else {
            cBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         */
        public C.Builder getCBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getCFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         */
        public COrBuilder getCOrBuilder() {
          if (cBuilder_ != null) {
            return cBuilder_.getMessageOrBuilder();
          } else {
            return c_ == null ?
                C.getDefaultInstance() : c_;
          }
        }
        /**
         * <code>optional .use_protobuf.blog2.A.B1.C c = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            C, C.Builder, COrBuilder>
            getCFieldBuilder() {
          if (cBuilder_ == null) {
            cBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                C, C.Builder, COrBuilder>(
                    getC(),
                    getParentForChildren(),
                    isClean());
            c_ = null;
          }
          return cBuilder_;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:use_protobuf.blog2.A.B1)
      }

      // @@protoc_insertion_point(class_scope:use_protobuf.blog2.A.B1)
      private static final B1 DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new B1();
      }

      public static B1 getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @Deprecated public static final com.google.protobuf.Parser<B1>
          PARSER = new com.google.protobuf.AbstractParser<B1>() {
        @Override
        public B1 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new B1(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<B1> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<B1> getParserForType() {
        return PARSER;
      }

      @Override
      public B1 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface B2OrBuilder extends
        // @@protoc_insertion_point(interface_extends:use_protobuf.blog2.A.B2)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 b = 1;</code>
       * @return Whether the b field is set.
       */
      boolean hasB();
      /**
       * <code>optional int32 b = 1;</code>
       * @return The b.
       */
      int getB();
    }
    /**
     * Protobuf type {@code use_protobuf.blog2.A.B2}
     */
    public  static final class B2 extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:use_protobuf.blog2.A.B2)
        B2OrBuilder {
    private static final long serialVersionUID = 0L;
      // Use B2.newBuilder() to construct.
      private B2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private B2() {
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new B2();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private B2(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                b_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test.internal_static_use_protobuf_blog2_A_B2_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test.internal_static_use_protobuf_blog2_A_B2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                B2.class, Builder.class);
      }

      private int bitField0_;
      public static final int B_FIELD_NUMBER = 1;
      private int b_;
      /**
       * <code>optional int32 b = 1;</code>
       * @return Whether the b field is set.
       */
      public boolean hasB() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 b = 1;</code>
       * @return The b.
       */
      public int getB() {
        return b_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt32(1, b_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, b_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof B2)) {
          return super.equals(obj);
        }
        B2 other = (B2) obj;

        if (hasB() != other.hasB()) return false;
        if (hasB()) {
          if (getB()
              != other.getB()) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasB()) {
          hash = (37 * hash) + B_FIELD_NUMBER;
          hash = (53 * hash) + getB();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static B2 parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static B2 parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static B2 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static B2 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static B2 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static B2 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static B2 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static B2 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static B2 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static B2 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static B2 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static B2 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(B2 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code use_protobuf.blog2.A.B2}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:use_protobuf.blog2.A.B2)
          B2OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Test.internal_static_use_protobuf_blog2_A_B2_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Test.internal_static_use_protobuf_blog2_A_B2_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  B2.class, Builder.class);
        }

        // Construct using use_protobuf.blog2.Test.A.B2.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          b_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Test.internal_static_use_protobuf_blog2_A_B2_descriptor;
        }

        @Override
        public B2 getDefaultInstanceForType() {
          return B2.getDefaultInstance();
        }

        @Override
        public B2 build() {
          B2 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public B2 buildPartial() {
          B2 result = new B2(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.b_ = b_;
            to_bitField0_ |= 0x00000001;
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof B2) {
            return mergeFrom((B2)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(B2 other) {
          if (other == B2.getDefaultInstance()) return this;
          if (other.hasB()) {
            setB(other.getB());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          B2 parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (B2) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int b_ ;
        /**
         * <code>optional int32 b = 1;</code>
         * @return Whether the b field is set.
         */
        public boolean hasB() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional int32 b = 1;</code>
         * @return The b.
         */
        public int getB() {
          return b_;
        }
        /**
         * <code>optional int32 b = 1;</code>
         * @param value The b to set.
         * @return This builder for chaining.
         */
        public Builder setB(int value) {
          bitField0_ |= 0x00000001;
          b_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 b = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearB() {
          bitField0_ = (bitField0_ & ~0x00000001);
          b_ = 0;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:use_protobuf.blog2.A.B2)
      }

      // @@protoc_insertion_point(class_scope:use_protobuf.blog2.A.B2)
      private static final B2 DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new B2();
      }

      public static B2 getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @Deprecated public static final com.google.protobuf.Parser<B2>
          PARSER = new com.google.protobuf.AbstractParser<B2>() {
        @Override
        public B2 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new B2(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<B2> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<B2> getParserForType() {
        return PARSER;
      }

      @Override
      public B2 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int A_FIELD_NUMBER = 1;
    private volatile Object a_;
    /**
     * <code>required string a = 1;</code>
     * @return Whether the a field is set.
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string a = 1;</code>
     * @return The a.
     */
    public String getA() {
      Object ref = a_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          a_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string a = 1;</code>
     * @return The bytes for a.
     */
    public com.google.protobuf.ByteString
        getABytes() {
      Object ref = a_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        a_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B1_FIELD_NUMBER = 2;
    private B1 b1_;
    /**
     * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
     * @return Whether the b1 field is set.
     */
    public boolean hasB1() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
     * @return The b1.
     */
    public B1 getB1() {
      return b1_ == null ? B1.getDefaultInstance() : b1_;
    }
    /**
     * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
     */
    public B1OrBuilder getB1OrBuilder() {
      return b1_ == null ? B1.getDefaultInstance() : b1_;
    }

    public static final int B2_FIELD_NUMBER = 3;
    private B2 b2_;
    /**
     * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
     * @return Whether the b2 field is set.
     */
    public boolean hasB2() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
     * @return The b2.
     */
    public B2 getB2() {
      return b2_ == null ? B2.getDefaultInstance() : b2_;
    }
    /**
     * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
     */
    public B2OrBuilder getB2OrBuilder() {
      return b2_ == null ? B2.getDefaultInstance() : b2_;
    }

    public static final int NUM_FIELD_NUMBER = 4;
    private int num_;
    /**
     * <code>optional int32 num = 4;</code>
     * @return Whether the num field is set.
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 num = 4;</code>
     * @return The num.
     */
    public int getNum() {
      return num_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, a_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getB1());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getB2());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, num_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, a_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getB1());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getB2());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, num_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof A)) {
        return super.equals(obj);
      }
      A other = (A) obj;

      if (hasA() != other.hasA()) return false;
      if (hasA()) {
        if (!getA()
            .equals(other.getA())) return false;
      }
      if (hasB1() != other.hasB1()) return false;
      if (hasB1()) {
        if (!getB1()
            .equals(other.getB1())) return false;
      }
      if (hasB2() != other.hasB2()) return false;
      if (hasB2()) {
        if (!getB2()
            .equals(other.getB2())) return false;
      }
      if (hasNum() != other.hasNum()) return false;
      if (hasNum()) {
        if (getNum()
            != other.getNum()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA().hashCode();
      }
      if (hasB1()) {
        hash = (37 * hash) + B1_FIELD_NUMBER;
        hash = (53 * hash) + getB1().hashCode();
      }
      if (hasB2()) {
        hash = (37 * hash) + B2_FIELD_NUMBER;
        hash = (53 * hash) + getB2().hashCode();
      }
      if (hasNum()) {
        hash = (37 * hash) + NUM_FIELD_NUMBER;
        hash = (53 * hash) + getNum();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static A parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static A parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static A parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static A parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static A parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static A parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(A prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code use_protobuf.blog2.A}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:use_protobuf.blog2.A)
        AOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test.internal_static_use_protobuf_blog2_A_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test.internal_static_use_protobuf_blog2_A_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                A.class, Builder.class);
      }

      // Construct using use_protobuf.blog2.Test.A.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getB1FieldBuilder();
          getB2FieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        a_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (b1Builder_ == null) {
          b1_ = null;
        } else {
          b1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (b2Builder_ == null) {
          b2_ = null;
        } else {
          b2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Test.internal_static_use_protobuf_blog2_A_descriptor;
      }

      @Override
      public A getDefaultInstanceForType() {
        return A.getDefaultInstance();
      }

      @Override
      public A build() {
        A result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public A buildPartial() {
        A result = new A(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.a_ = a_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (b1Builder_ == null) {
            result.b1_ = b1_;
          } else {
            result.b1_ = b1Builder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (b2Builder_ == null) {
            result.b2_ = b2_;
          } else {
            result.b2_ = b2Builder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.num_ = num_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof A) {
          return mergeFrom((A)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(A other) {
        if (other == A.getDefaultInstance()) return this;
        if (other.hasA()) {
          bitField0_ |= 0x00000001;
          a_ = other.a_;
          onChanged();
        }
        if (other.hasB1()) {
          mergeB1(other.getB1());
        }
        if (other.hasB2()) {
          mergeB2(other.getB2());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasA()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        A parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (A) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object a_ = "";
      /**
       * <code>required string a = 1;</code>
       * @return Whether the a field is set.
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string a = 1;</code>
       * @return The a.
       */
      public String getA() {
        Object ref = a_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            a_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string a = 1;</code>
       * @return The bytes for a.
       */
      public com.google.protobuf.ByteString
          getABytes() {
        Object ref = a_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          a_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string a = 1;</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string a = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = getDefaultInstance().getA();
        onChanged();
        return this;
      }
      /**
       * <code>required string a = 1;</code>
       * @param value The bytes for a to set.
       * @return This builder for chaining.
       */
      public Builder setABytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        a_ = value;
        onChanged();
        return this;
      }

      private B1 b1_;
      private com.google.protobuf.SingleFieldBuilderV3<
          B1, B1.Builder, B1OrBuilder> b1Builder_;
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       * @return Whether the b1 field is set.
       */
      public boolean hasB1() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       * @return The b1.
       */
      public B1 getB1() {
        if (b1Builder_ == null) {
          return b1_ == null ? B1.getDefaultInstance() : b1_;
        } else {
          return b1Builder_.getMessage();
        }
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       */
      public Builder setB1(B1 value) {
        if (b1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          b1_ = value;
          onChanged();
        } else {
          b1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       */
      public Builder setB1(
          B1.Builder builderForValue) {
        if (b1Builder_ == null) {
          b1_ = builderForValue.build();
          onChanged();
        } else {
          b1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       */
      public Builder mergeB1(B1 value) {
        if (b1Builder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              b1_ != null &&
              b1_ != B1.getDefaultInstance()) {
            b1_ =
              B1.newBuilder(b1_).mergeFrom(value).buildPartial();
          } else {
            b1_ = value;
          }
          onChanged();
        } else {
          b1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       */
      public Builder clearB1() {
        if (b1Builder_ == null) {
          b1_ = null;
          onChanged();
        } else {
          b1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       */
      public B1.Builder getB1Builder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getB1FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       */
      public B1OrBuilder getB1OrBuilder() {
        if (b1Builder_ != null) {
          return b1Builder_.getMessageOrBuilder();
        } else {
          return b1_ == null ?
              B1.getDefaultInstance() : b1_;
        }
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B1 b1 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          B1, B1.Builder, B1OrBuilder>
          getB1FieldBuilder() {
        if (b1Builder_ == null) {
          b1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              B1, B1.Builder, B1OrBuilder>(
                  getB1(),
                  getParentForChildren(),
                  isClean());
          b1_ = null;
        }
        return b1Builder_;
      }

      private B2 b2_;
      private com.google.protobuf.SingleFieldBuilderV3<
          B2, B2.Builder, B2OrBuilder> b2Builder_;
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       * @return Whether the b2 field is set.
       */
      public boolean hasB2() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       * @return The b2.
       */
      public B2 getB2() {
        if (b2Builder_ == null) {
          return b2_ == null ? B2.getDefaultInstance() : b2_;
        } else {
          return b2Builder_.getMessage();
        }
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       */
      public Builder setB2(B2 value) {
        if (b2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          b2_ = value;
          onChanged();
        } else {
          b2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       */
      public Builder setB2(
          B2.Builder builderForValue) {
        if (b2Builder_ == null) {
          b2_ = builderForValue.build();
          onChanged();
        } else {
          b2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       */
      public Builder mergeB2(B2 value) {
        if (b2Builder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              b2_ != null &&
              b2_ != B2.getDefaultInstance()) {
            b2_ =
              B2.newBuilder(b2_).mergeFrom(value).buildPartial();
          } else {
            b2_ = value;
          }
          onChanged();
        } else {
          b2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       */
      public Builder clearB2() {
        if (b2Builder_ == null) {
          b2_ = null;
          onChanged();
        } else {
          b2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       */
      public B2.Builder getB2Builder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getB2FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       */
      public B2OrBuilder getB2OrBuilder() {
        if (b2Builder_ != null) {
          return b2Builder_.getMessageOrBuilder();
        } else {
          return b2_ == null ?
              B2.getDefaultInstance() : b2_;
        }
      }
      /**
       * <code>optional .use_protobuf.blog2.A.B2 b2 = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          B2, B2.Builder, B2OrBuilder>
          getB2FieldBuilder() {
        if (b2Builder_ == null) {
          b2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              B2, B2.Builder, B2OrBuilder>(
                  getB2(),
                  getParentForChildren(),
                  isClean());
          b2_ = null;
        }
        return b2Builder_;
      }

      private int num_ ;
      /**
       * <code>optional int32 num = 4;</code>
       * @return Whether the num field is set.
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 num = 4;</code>
       * @return The num.
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional int32 num = 4;</code>
       * @param value The num to set.
       * @return This builder for chaining.
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000008;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        num_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:use_protobuf.blog2.A)
    }

    // @@protoc_insertion_point(class_scope:use_protobuf.blog2.A)
    private static final A DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new A();
    }

    public static A getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<A>
        PARSER = new com.google.protobuf.AbstractParser<A>() {
      @Override
      public A parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new A(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<A> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<A> getParserForType() {
      return PARSER;
    }

    @Override
    public A getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_blog2_A_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_blog2_A_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_blog2_A_B1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_blog2_A_B1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_blog2_A_B1_C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_blog2_A_B1_C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_blog2_A_B2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_blog2_A_B2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntest.proto\022\022use_protobuf.blog2\"\300\001\n\001A\022\t" +
      "\n\001a\030\001 \002(\t\022$\n\002b1\030\002 \001(\0132\030.use_protobuf.blo" +
      "g2.A.B1\022$\n\002b2\030\003 \001(\0132\030.use_protobuf.blog2" +
      ".A.B2\022\013\n\003num\030\004 \001(\005\032F\n\002B1\022\t\n\001b\030\001 \001(\t\022%\n\001c" +
      "\030\002 \001(\0132\032.use_protobuf.blog2.A.B1.C\032\016\n\001C\022" +
      "\t\n\001c\030\001 \001(\t\032\017\n\002B2\022\t\n\001b\030\001 \001(\005"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_use_protobuf_blog2_A_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_use_protobuf_blog2_A_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_blog2_A_descriptor,
        new String[] { "A", "B1", "B2", "Num", });
    internal_static_use_protobuf_blog2_A_B1_descriptor =
      internal_static_use_protobuf_blog2_A_descriptor.getNestedTypes().get(0);
    internal_static_use_protobuf_blog2_A_B1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_blog2_A_B1_descriptor,
        new String[] { "B", "C", });
    internal_static_use_protobuf_blog2_A_B1_C_descriptor =
      internal_static_use_protobuf_blog2_A_B1_descriptor.getNestedTypes().get(0);
    internal_static_use_protobuf_blog2_A_B1_C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_blog2_A_B1_C_descriptor,
        new String[] { "C", });
    internal_static_use_protobuf_blog2_A_B2_descriptor =
      internal_static_use_protobuf_blog2_A_descriptor.getNestedTypes().get(1);
    internal_static_use_protobuf_blog2_A_B2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_blog2_A_B2_descriptor,
        new String[] { "B", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
