// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

package use_protobuf.package3;

public final class Info {
  private Info() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FooOrBuilder extends
      // @@protoc_insertion_point(interface_extends:use_protobuf.package3.Foo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 val = 1;</code>
     * @return Whether the val field is set.
     */
    boolean hasVal();
    /**
     * <code>optional int32 val = 1;</code>
     * @return The val.
     */
    int getVal();
  }
  /**
   * Protobuf type {@code use_protobuf.package3.Foo}
   */
  public  static final class Foo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:use_protobuf.package3.Foo)
      FooOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Foo.newBuilder() to construct.
    private Foo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Foo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Foo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Foo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              val_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Foo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Foo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              use_protobuf.package3.Info.Foo.class, use_protobuf.package3.Info.Foo.Builder.class);
    }

    private int bitField0_;
    public static final int VAL_FIELD_NUMBER = 1;
    private int val_;
    /**
     * <code>optional int32 val = 1;</code>
     * @return Whether the val field is set.
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 val = 1;</code>
     * @return The val.
     */
    public int getVal() {
      return val_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, val_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, val_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof use_protobuf.package3.Info.Foo)) {
        return super.equals(obj);
      }
      use_protobuf.package3.Info.Foo other = (use_protobuf.package3.Info.Foo) obj;

      if (hasVal() != other.hasVal()) return false;
      if (hasVal()) {
        if (getVal()
            != other.getVal()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVal()) {
        hash = (37 * hash) + VAL_FIELD_NUMBER;
        hash = (53 * hash) + getVal();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static use_protobuf.package3.Info.Foo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(use_protobuf.package3.Info.Foo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code use_protobuf.package3.Foo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:use_protobuf.package3.Foo)
        use_protobuf.package3.Info.FooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Foo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Foo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                use_protobuf.package3.Info.Foo.class, use_protobuf.package3.Info.Foo.Builder.class);
      }

      // Construct using use_protobuf.package3.Info.Foo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        val_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Foo_descriptor;
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Foo getDefaultInstanceForType() {
        return use_protobuf.package3.Info.Foo.getDefaultInstance();
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Foo build() {
        use_protobuf.package3.Info.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Foo buildPartial() {
        use_protobuf.package3.Info.Foo result = new use_protobuf.package3.Info.Foo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.val_ = val_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof use_protobuf.package3.Info.Foo) {
          return mergeFrom((use_protobuf.package3.Info.Foo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(use_protobuf.package3.Info.Foo other) {
        if (other == use_protobuf.package3.Info.Foo.getDefaultInstance()) return this;
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        use_protobuf.package3.Info.Foo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (use_protobuf.package3.Info.Foo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int val_ ;
      /**
       * <code>optional int32 val = 1;</code>
       * @return Whether the val field is set.
       */
      public boolean hasVal() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 val = 1;</code>
       * @return The val.
       */
      public int getVal() {
        return val_;
      }
      /**
       * <code>optional int32 val = 1;</code>
       * @param value The val to set.
       * @return This builder for chaining.
       */
      public Builder setVal(int value) {
        bitField0_ |= 0x00000001;
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:use_protobuf.package3.Foo)
    }

    // @@protoc_insertion_point(class_scope:use_protobuf.package3.Foo)
    private static final use_protobuf.package3.Info.Foo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new use_protobuf.package3.Info.Foo();
    }

    public static use_protobuf.package3.Info.Foo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Foo>
        PARSER = new com.google.protobuf.AbstractParser<Foo>() {
      @java.lang.Override
      public Foo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Foo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Foo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Foo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public use_protobuf.package3.Info.Foo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:use_protobuf.package3.Bar)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
     * @return Whether the foo field is set.
     */
    boolean hasFoo();
    /**
     * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
     * @return The foo.
     */
    use_protobuf.package3.Info.Foo getFoo();
    /**
     * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
     */
    use_protobuf.package3.Info.FooOrBuilder getFooOrBuilder();
  }
  /**
   * Protobuf type {@code use_protobuf.package3.Bar}
   */
  public  static final class Bar extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:use_protobuf.package3.Bar)
      BarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Bar.newBuilder() to construct.
    private Bar(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bar() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Bar();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Bar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              use_protobuf.package3.Info.Foo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = foo_.toBuilder();
              }
              foo_ = input.readMessage(use_protobuf.package3.Info.Foo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(foo_);
                foo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Bar_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Bar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              use_protobuf.package3.Info.Bar.class, use_protobuf.package3.Info.Bar.Builder.class);
    }

    private int bitField0_;
    public static final int FOO_FIELD_NUMBER = 1;
    private use_protobuf.package3.Info.Foo foo_;
    /**
     * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
     * @return Whether the foo field is set.
     */
    public boolean hasFoo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
     * @return The foo.
     */
    public use_protobuf.package3.Info.Foo getFoo() {
      return foo_ == null ? use_protobuf.package3.Info.Foo.getDefaultInstance() : foo_;
    }
    /**
     * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
     */
    public use_protobuf.package3.Info.FooOrBuilder getFooOrBuilder() {
      return foo_ == null ? use_protobuf.package3.Info.Foo.getDefaultInstance() : foo_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getFoo());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFoo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof use_protobuf.package3.Info.Bar)) {
        return super.equals(obj);
      }
      use_protobuf.package3.Info.Bar other = (use_protobuf.package3.Info.Bar) obj;

      if (hasFoo() != other.hasFoo()) return false;
      if (hasFoo()) {
        if (!getFoo()
            .equals(other.getFoo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFoo()) {
        hash = (37 * hash) + FOO_FIELD_NUMBER;
        hash = (53 * hash) + getFoo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static use_protobuf.package3.Info.Bar parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Bar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Bar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Bar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(use_protobuf.package3.Info.Bar prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code use_protobuf.package3.Bar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:use_protobuf.package3.Bar)
        use_protobuf.package3.Info.BarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Bar_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Bar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                use_protobuf.package3.Info.Bar.class, use_protobuf.package3.Info.Bar.Builder.class);
      }

      // Construct using use_protobuf.package3.Info.Bar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFooFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fooBuilder_ == null) {
          foo_ = null;
        } else {
          fooBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Bar_descriptor;
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Bar getDefaultInstanceForType() {
        return use_protobuf.package3.Info.Bar.getDefaultInstance();
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Bar build() {
        use_protobuf.package3.Info.Bar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Bar buildPartial() {
        use_protobuf.package3.Info.Bar result = new use_protobuf.package3.Info.Bar(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (fooBuilder_ == null) {
            result.foo_ = foo_;
          } else {
            result.foo_ = fooBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof use_protobuf.package3.Info.Bar) {
          return mergeFrom((use_protobuf.package3.Info.Bar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(use_protobuf.package3.Info.Bar other) {
        if (other == use_protobuf.package3.Info.Bar.getDefaultInstance()) return this;
        if (other.hasFoo()) {
          mergeFoo(other.getFoo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        use_protobuf.package3.Info.Bar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (use_protobuf.package3.Info.Bar) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private use_protobuf.package3.Info.Foo foo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          use_protobuf.package3.Info.Foo, use_protobuf.package3.Info.Foo.Builder, use_protobuf.package3.Info.FooOrBuilder> fooBuilder_;
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       * @return Whether the foo field is set.
       */
      public boolean hasFoo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       * @return The foo.
       */
      public use_protobuf.package3.Info.Foo getFoo() {
        if (fooBuilder_ == null) {
          return foo_ == null ? use_protobuf.package3.Info.Foo.getDefaultInstance() : foo_;
        } else {
          return fooBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       */
      public Builder setFoo(use_protobuf.package3.Info.Foo value) {
        if (fooBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          foo_ = value;
          onChanged();
        } else {
          fooBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       */
      public Builder setFoo(
          use_protobuf.package3.Info.Foo.Builder builderForValue) {
        if (fooBuilder_ == null) {
          foo_ = builderForValue.build();
          onChanged();
        } else {
          fooBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       */
      public Builder mergeFoo(use_protobuf.package3.Info.Foo value) {
        if (fooBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              foo_ != null &&
              foo_ != use_protobuf.package3.Info.Foo.getDefaultInstance()) {
            foo_ =
              use_protobuf.package3.Info.Foo.newBuilder(foo_).mergeFrom(value).buildPartial();
          } else {
            foo_ = value;
          }
          onChanged();
        } else {
          fooBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       */
      public Builder clearFoo() {
        if (fooBuilder_ == null) {
          foo_ = null;
          onChanged();
        } else {
          fooBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       */
      public use_protobuf.package3.Info.Foo.Builder getFooBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFooFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       */
      public use_protobuf.package3.Info.FooOrBuilder getFooOrBuilder() {
        if (fooBuilder_ != null) {
          return fooBuilder_.getMessageOrBuilder();
        } else {
          return foo_ == null ?
              use_protobuf.package3.Info.Foo.getDefaultInstance() : foo_;
        }
      }
      /**
       * <code>optional .use_protobuf.package3.Foo foo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          use_protobuf.package3.Info.Foo, use_protobuf.package3.Info.Foo.Builder, use_protobuf.package3.Info.FooOrBuilder> 
          getFooFieldBuilder() {
        if (fooBuilder_ == null) {
          fooBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              use_protobuf.package3.Info.Foo, use_protobuf.package3.Info.Foo.Builder, use_protobuf.package3.Info.FooOrBuilder>(
                  getFoo(),
                  getParentForChildren(),
                  isClean());
          foo_ = null;
        }
        return fooBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:use_protobuf.package3.Bar)
    }

    // @@protoc_insertion_point(class_scope:use_protobuf.package3.Bar)
    private static final use_protobuf.package3.Info.Bar DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new use_protobuf.package3.Info.Bar();
    }

    public static use_protobuf.package3.Info.Bar getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Bar>
        PARSER = new com.google.protobuf.AbstractParser<Bar>() {
      @java.lang.Override
      public Bar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bar(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bar> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bar> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public use_protobuf.package3.Info.Bar getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BazOrBuilder extends
      // @@protoc_insertion_point(interface_extends:use_protobuf.package3.Baz)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
     * @return Whether the bar field is set.
     */
    boolean hasBar();
    /**
     * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
     * @return The bar.
     */
    use_protobuf.package3.Info.Bar getBar();
    /**
     * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
     */
    use_protobuf.package3.Info.BarOrBuilder getBarOrBuilder();
  }
  /**
   * Protobuf type {@code use_protobuf.package3.Baz}
   */
  public  static final class Baz extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:use_protobuf.package3.Baz)
      BazOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Baz.newBuilder() to construct.
    private Baz(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Baz() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Baz();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Baz(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              use_protobuf.package3.Info.Bar.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = bar_.toBuilder();
              }
              bar_ = input.readMessage(use_protobuf.package3.Info.Bar.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bar_);
                bar_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Baz_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Baz_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              use_protobuf.package3.Info.Baz.class, use_protobuf.package3.Info.Baz.Builder.class);
    }

    private int bitField0_;
    public static final int BAR_FIELD_NUMBER = 1;
    private use_protobuf.package3.Info.Bar bar_;
    /**
     * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
     * @return Whether the bar field is set.
     */
    public boolean hasBar() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
     * @return The bar.
     */
    public use_protobuf.package3.Info.Bar getBar() {
      return bar_ == null ? use_protobuf.package3.Info.Bar.getDefaultInstance() : bar_;
    }
    /**
     * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
     */
    public use_protobuf.package3.Info.BarOrBuilder getBarOrBuilder() {
      return bar_ == null ? use_protobuf.package3.Info.Bar.getDefaultInstance() : bar_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getBar());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBar());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof use_protobuf.package3.Info.Baz)) {
        return super.equals(obj);
      }
      use_protobuf.package3.Info.Baz other = (use_protobuf.package3.Info.Baz) obj;

      if (hasBar() != other.hasBar()) return false;
      if (hasBar()) {
        if (!getBar()
            .equals(other.getBar())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBar()) {
        hash = (37 * hash) + BAR_FIELD_NUMBER;
        hash = (53 * hash) + getBar().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static use_protobuf.package3.Info.Baz parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Baz parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Baz parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static use_protobuf.package3.Info.Baz parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(use_protobuf.package3.Info.Baz prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code use_protobuf.package3.Baz}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:use_protobuf.package3.Baz)
        use_protobuf.package3.Info.BazOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Baz_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Baz_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                use_protobuf.package3.Info.Baz.class, use_protobuf.package3.Info.Baz.Builder.class);
      }

      // Construct using use_protobuf.package3.Info.Baz.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBarFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (barBuilder_ == null) {
          bar_ = null;
        } else {
          barBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return use_protobuf.package3.Info.internal_static_use_protobuf_package3_Baz_descriptor;
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Baz getDefaultInstanceForType() {
        return use_protobuf.package3.Info.Baz.getDefaultInstance();
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Baz build() {
        use_protobuf.package3.Info.Baz result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public use_protobuf.package3.Info.Baz buildPartial() {
        use_protobuf.package3.Info.Baz result = new use_protobuf.package3.Info.Baz(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (barBuilder_ == null) {
            result.bar_ = bar_;
          } else {
            result.bar_ = barBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof use_protobuf.package3.Info.Baz) {
          return mergeFrom((use_protobuf.package3.Info.Baz)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(use_protobuf.package3.Info.Baz other) {
        if (other == use_protobuf.package3.Info.Baz.getDefaultInstance()) return this;
        if (other.hasBar()) {
          mergeBar(other.getBar());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        use_protobuf.package3.Info.Baz parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (use_protobuf.package3.Info.Baz) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private use_protobuf.package3.Info.Bar bar_;
      private com.google.protobuf.SingleFieldBuilderV3<
          use_protobuf.package3.Info.Bar, use_protobuf.package3.Info.Bar.Builder, use_protobuf.package3.Info.BarOrBuilder> barBuilder_;
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       * @return Whether the bar field is set.
       */
      public boolean hasBar() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       * @return The bar.
       */
      public use_protobuf.package3.Info.Bar getBar() {
        if (barBuilder_ == null) {
          return bar_ == null ? use_protobuf.package3.Info.Bar.getDefaultInstance() : bar_;
        } else {
          return barBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       */
      public Builder setBar(use_protobuf.package3.Info.Bar value) {
        if (barBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bar_ = value;
          onChanged();
        } else {
          barBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       */
      public Builder setBar(
          use_protobuf.package3.Info.Bar.Builder builderForValue) {
        if (barBuilder_ == null) {
          bar_ = builderForValue.build();
          onChanged();
        } else {
          barBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       */
      public Builder mergeBar(use_protobuf.package3.Info.Bar value) {
        if (barBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              bar_ != null &&
              bar_ != use_protobuf.package3.Info.Bar.getDefaultInstance()) {
            bar_ =
              use_protobuf.package3.Info.Bar.newBuilder(bar_).mergeFrom(value).buildPartial();
          } else {
            bar_ = value;
          }
          onChanged();
        } else {
          barBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       */
      public Builder clearBar() {
        if (barBuilder_ == null) {
          bar_ = null;
          onChanged();
        } else {
          barBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       */
      public use_protobuf.package3.Info.Bar.Builder getBarBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBarFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       */
      public use_protobuf.package3.Info.BarOrBuilder getBarOrBuilder() {
        if (barBuilder_ != null) {
          return barBuilder_.getMessageOrBuilder();
        } else {
          return bar_ == null ?
              use_protobuf.package3.Info.Bar.getDefaultInstance() : bar_;
        }
      }
      /**
       * <code>optional .use_protobuf.package3.Bar bar = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          use_protobuf.package3.Info.Bar, use_protobuf.package3.Info.Bar.Builder, use_protobuf.package3.Info.BarOrBuilder> 
          getBarFieldBuilder() {
        if (barBuilder_ == null) {
          barBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              use_protobuf.package3.Info.Bar, use_protobuf.package3.Info.Bar.Builder, use_protobuf.package3.Info.BarOrBuilder>(
                  getBar(),
                  getParentForChildren(),
                  isClean());
          bar_ = null;
        }
        return barBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:use_protobuf.package3.Baz)
    }

    // @@protoc_insertion_point(class_scope:use_protobuf.package3.Baz)
    private static final use_protobuf.package3.Info.Baz DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new use_protobuf.package3.Info.Baz();
    }

    public static use_protobuf.package3.Info.Baz getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Baz>
        PARSER = new com.google.protobuf.AbstractParser<Baz>() {
      @java.lang.Override
      public Baz parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Baz(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Baz> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Baz> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public use_protobuf.package3.Info.Baz getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_package3_Foo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_package3_Foo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_package3_Bar_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_package3_Bar_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_use_protobuf_package3_Baz_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_use_protobuf_package3_Baz_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ninfo.proto\022\025use_protobuf.package3\"\022\n\003F" +
      "oo\022\013\n\003val\030\001 \001(\005\".\n\003Bar\022\'\n\003foo\030\001 \001(\0132\032.us" +
      "e_protobuf.package3.Foo\".\n\003Baz\022\'\n\003bar\030\001 " +
      "\001(\0132\032.use_protobuf.package3.BarB\027\n\025use_p" +
      "rotobuf.package3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_use_protobuf_package3_Foo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_use_protobuf_package3_Foo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_package3_Foo_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_use_protobuf_package3_Bar_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_use_protobuf_package3_Bar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_package3_Bar_descriptor,
        new java.lang.String[] { "Foo", });
    internal_static_use_protobuf_package3_Baz_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_use_protobuf_package3_Baz_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_use_protobuf_package3_Baz_descriptor,
        new java.lang.String[] { "Bar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
